// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("netbird");

/**
 * NetBird Management API URL, can be also set through NB_MANAGEMENT_URL Environment Variable, value defined in Terraform files takes precedence
 */
export declare const managementUrl: string | undefined;
Object.defineProperty(exports, "managementUrl", {
    get() {
        return __config.get("managementUrl");
    },
    enumerable: true,
});

/**
 * Account ID to impersonate, can be also set through NB_ACCOUNT Environment Variable, value defined in Terraform files takes precedence
 */
export declare const tenantAccount: string | undefined;
Object.defineProperty(exports, "tenantAccount", {
    get() {
        return __config.get("tenantAccount");
    },
    enumerable: true,
});

/**
 * Admin PAT for NetBird Management Server, can be also set through NB_PAT Environment Variable, value defined in Terraform files takes precedence
 */
export declare const token: string | undefined;
Object.defineProperty(exports, "token", {
    get() {
        return __config.get("token");
    },
    enumerable: true,
});

