import base from "@anarkisti/eslint-config";

// `sdks/` is generated by `pulumi package add` and regenerated whole, so it is
// linted no more than it is formatted — a rule it broke would be a finding
// about somebody else's code generator.
export default [...base, { ignores: ["build/", "sdks/"] }];
