/**
 * What the house-app template produces, written out.
 *
 * A constructor that derives twenty lines from six is only reviewable if the
 * twenty are stated somewhere a reader can check them against, and a snapshot is
 * not that place: it is regenerated by the tool that failed, so a convention
 * could change and the diff would be accepted as noise. So the expansion below
 * is a literal `ServiceSpec`, spelled by hand. The rest holds what a stamped
 * entry has to keep: an override replaces a derived value, the merged blocks add
 * and refuse two owners, the network follows the login, and a stamped entry
 * passes the invariants a literal one does — asserted over a composition that
 * contains one, since the committed catalogs contain none.
 */

import { describe, expect, it } from "vitest";

import { priceMemory, PROFILES } from "../src/config/profiles";
import { composeCatalog, EXAMPLE_SERVICES } from "../src/config/services";
import {
  catalogOf,
  deploymentGaps,
  runSetup,
  secretFields,
  secretsPath,
  type ServiceSpec,
  subdomainOf,
} from "../src/config/spec";
import { houseApp, type HouseAppOptions } from "../src/config/templates/houseApp";
import { renderQuadlet } from "../src/render/quadlet";
import { CAP_HEADROOM } from "./caps";
import { HOUSE } from "./house";

/** Five of the six facts. The sixth is how a visitor proves who they are. */
const FACTS = {
  name: "atlas",
  description: "A house application, as a fixture",
  image: "ghcr.io/example/atlas:main",
  port: 3010,
  memory: { max: 96, measuredMb: 30 },
};

/**
 * The fixture's own vocabulary, deliberately not the shape a prefix rule would
 * have produced: `ATLAS_LISTEN` and `ATLAS_DB` are what this application reads,
 * and no template gets to know that.
 */
const OIDC_STAMP: HouseAppOptions = {
  ...FACTS,
  auth: "oidc",
  identityItem: "kanidm",
  env: { ATLAS_LISTEN: "127.0.0.1:3010", ATLAS_DB: "/data/atlas.db" },
};
const EDGE_STAMP: HouseAppOptions = { ...FACTS, auth: "edge" };
const OPEN_STAMP: HouseAppOptions = { ...FACTS, auth: "open" };

const OIDC_ENV = {
  OIDC_ISSUER: "https://idm.example.test/oauth2/openid/atlas",
  OIDC_CLIENT_ID: "atlas",
  OIDC_REDIRECT_URL: "https://atlas.example.test/auth/callback",
};

/**
 * The stamped entry beside the five keel ships. Roles resolve over what is
 * deployed together, so this is what gives the fixture an identity provider to
 * be a client of and a proxy to be routed by — the same composition a deploy
 * sees, rather than a hand-made role.
 */
const withStamped = (spec: ServiceSpec) => composeCatalog(EXAMPLE_SERVICES, [spec]);
const setupOf = (spec: ServiceSpec) => runSetup(spec, HOUSE, catalogOf(withStamped(spec)));

describe("the expansion is written down", () => {
  const { setup, ...stamped } = houseApp(OIDC_STAMP);

  it("is the entry somebody would otherwise have written by hand", () => {
    const literal: Omit<ServiceSpec, "setup"> = {
      name: "atlas",
      description: "A house application, as a fixture",
      // A tag rather than a digest: an application built by its own CI has its
      // digest resolved when the deploy runs.
      image: "ghcr.io/example/atlas:main",
      port: 3010,
      // The tier is not an option: the image's slice budgets are the sum of the
      // core tier's caps, so an application there would change the artefact.
      memory: { max: 96, measuredMb: 30, tier: "apps" },
      subdomain: "atlas",
      publicDns: true,
      auth: "oidc",
      // A client of the issuer reaches it through the issuer's own vhost, whose
      // allowlist admits the LAN and the mesh — so the host's stack, exactly as
      // the gate has it, and not the bridge a gated application keeps.
      egress: "host",
      // Passed through exactly as the entry stated it: the names and the values
      // are the application's, so the template neither writes, renames nor reads them.
      env: { ATLAS_LISTEN: "127.0.0.1:3010", ATLAS_DB: "/data/atlas.db" },
      secretEnv: {
        SESSION_KEY: "session_key",
        // The provider generates it and keeps it with its own credentials, so
        // the client names the item as well as the field.
        OIDC_CLIENT_SECRET: { item: "kanidm", field: "atlas_client_secret" },
      },
      // `U` because the image runs as uid 1000 and the unit makes the directory as root.
      mounts: ["/var/lib/atlas:/data:Z,U"],
      backup: true,
    };
    expect(stamped).toEqual(literal);
    // Compared apart because it is a function: what it returns is the next test.
    expect(setup).toBeTypeOf("function");
  });

  it("composes the client's two URLs from the resolved role, after the entry's own", () => {
    // Neither URL is stated anywhere: the issuer comes from the provider's vhost
    // and this entry's client id, the redirect from this entry's vhost and the
    // callback path every one of these applications serves.
    const spec = houseApp(OIDC_STAMP);
    expect(setupOf(spec)).toEqual({ env: OIDC_ENV });
    // The restart trigger is a hash of the quadlet body, so insertion order is
    // load-bearing: the entry's own first, then what the setup composed.
    expect(renderQuadlet(spec, setupOf(spec)?.env).match(/^Environment=(\w+)=/gm)).toEqual(
      ["ATLAS_LISTEN", "ATLAS_DB", ...Object.keys(OIDC_ENV)].map((v) => `Environment=${v}=`),
    );
  });
});

describe("an override replaces what would have been derived", () => {
  it("takes any other spec field, and keeps every convention it did not name", () => {
    const overrides = {
      subdomain: "maps",
      publicDns: false,
      backup: false,
      backupExclude: ["/var/lib/atlas/cache"],
      egress: "open",
      healthCmd: "curl -fsS localhost:3010/health",
      ingress: { lanTcp: [3010] },
      tlsUpstream: true,
      cmd: "serve",
      vaultItem: "shared",
      dependsOn: ["other"],
    } satisfies Partial<ServiceSpec>;
    const spec = houseApp({ ...EDGE_STAMP, ...overrides });
    expect(spec).toMatchObject(overrides);
    expect(spec.mounts).toEqual(["/var/lib/atlas:/data:Z,U"]);
    expect(secretFields(spec)).toEqual({ SESSION_KEY: { item: "shared", field: "session_key" } });
    expect(spec.memory.tier).toBe("apps");
  });

  it("follows the vhost and the data directory where nothing overrides them", () => {
    // `null` is a different statement from an unset field: no vhost, and with it
    // no record to publish; no data, and with it nothing to snapshot.
    const nothing = houseApp({ ...OPEN_STAMP, subdomain: null, dataDir: null });
    expect(subdomainOf(nothing)).toBeNull();
    expect(nothing).toMatchObject({ publicDns: false, backup: false });
    expect(nothing.mounts).toBeUndefined();
    expect(houseApp({ ...OPEN_STAMP, dataDir: "/var/opt/atlas" }).mounts).toEqual([
      "/var/lib/atlas:/var/opt/atlas:Z,U",
    ]);
  });

  it("refuses a name it cannot turn into a label", () => {
    // A dash is the one separator the unit, the vhost and the directory all accept.
    expect(houseApp({ ...EDGE_STAMP, name: "my-app" }).mounts).toEqual([
      "/var/lib/my-app:/data:Z,U",
    ]);
    for (const name of ["my.app", "My App", "9lives", ""]) {
      expect(() => houseApp({ ...EDGE_STAMP, name }), name).toThrow(/derive from/);
    }
  });
});

describe("the merged blocks add rather than replace", () => {
  const spec = houseApp({
    ...OIDC_STAMP,
    env: { ...OIDC_STAMP.env, ATLAS_LOG: "info" },
    secretEnv: { ATLAS_API_TOKEN: "api_token" },
    mounts: ["/var/mnt/media:/media:ro"],
    setup: ({ installation: { smtp } }) => ({
      env: { ATLAS_SMTP_HOST: smtp.host },
      files: [{ name: "rules", path: "/etc/atlas/rules.yaml", content: "rules: []" }],
    }),
  });

  it("keeps the entry's own beside what it derives", () => {
    expect(spec.env).toEqual({ ...OIDC_STAMP.env, ATLAS_LOG: "info" });
    expect(secretFields(spec)).toEqual({
      SESSION_KEY: { item: "atlas", field: "session_key" },
      OIDC_CLIENT_SECRET: { item: "kanidm", field: "atlas_client_secret" },
      ATLAS_API_TOKEN: { item: "atlas", field: "api_token" },
    });
    expect(spec.mounts).toEqual(["/var/lib/atlas:/data:Z,U", "/var/mnt/media:/media:ro"]);
    expect(setupOf(spec)).toEqual({
      env: { ...OIDC_ENV, ATLAS_SMTP_HOST: "smtp.example.test" },
      files: [{ name: "rules", path: "/etc/atlas/rules.yaml", content: "rules: []" }],
    });
  });

  it("refuses a variable with two owners, naming it", () => {
    // Precedence is the alternative and there is no honest one: a caller
    // silently overriding a derived variable makes the stamp a suggestion.
    expect(() => houseApp({ ...OIDC_STAMP, secretEnv: { SESSION_KEY: "elsewhere" } })).toThrow(
      /SESSION_KEY/,
    );
    const clash = houseApp({ ...OIDC_STAMP, setup: () => ({ env: { OIDC_ISSUER: "https://x" } }) });
    expect(() => setupOf(clash)).toThrow(/OIDC_ISSUER/);
  });

  it("refuses a mount with two owners, naming its source", () => {
    // Two Volume= lines for one host path is not something quadlet resolves —
    // it renders both, with whichever flags land last, so a caller mount that
    // reuses the derived data mount's own source is refused rather than doubled.
    expect(() => houseApp({ ...OIDC_STAMP, mounts: ["/var/lib/atlas:/data:ro"] })).toThrow(
      /\/var\/lib\/atlas/,
    );
  });
});

describe("how a visitor proves who they are", () => {
  it("gives each mode the secrets it needs and no more", () => {
    // Open: no session, no client, and no installation-shaped half at all —
    // which is what makes `setup` absent rather than empty.
    const open = houseApp(OPEN_STAMP);
    expect(open.secretEnv).toBeUndefined();
    expect(secretsPath(open)).toBeNull();
    expect(open.setup).toBeUndefined();
    // Gated: the gate authenticates the request; what the application does with
    // that identity afterwards is a cookie it signs itself.
    const edge = houseApp(EDGE_STAMP);
    expect(secretFields(edge)).toEqual({ SESSION_KEY: { item: "atlas", field: "session_key" } });
    expect(edge.setup).toBeUndefined();
    // A client: both, plus the three variables it discovers itself with — and a
    // refusal at the deploy, not the first login, when nothing deployed is an issuer.
    const oidc = houseApp(OIDC_STAMP);
    expect(Object.keys(secretFields(oidc))).toEqual(["SESSION_KEY", "OIDC_CLIENT_SECRET"]);
    expect(Object.keys(setupOf(oidc)?.env ?? {})).toEqual(Object.keys(OIDC_ENV));
    expect(() => runSetup(oidc, HOUSE, catalogOf([oidc]))).toThrow(/identity role/);
  });
});

describe("the network follows the login", () => {
  it("puts a client of the issuer on the host's stack, and everything else on the bridge", () => {
    // The back channel is the application's own request to the issuer's vhost,
    // whose allowlist admits the LAN and the mesh. The host's address is in both
    // sets; a bridge address is in neither.
    const client = houseApp(OIDC_STAMP);
    expect(client.egress).toBe("host");
    const quadlet = renderQuadlet(client, setupOf(client)?.env);
    expect(quadlet).toContain("Network=host");
    expect(quadlet).not.toContain("PublishPort=");
    for (const options of [EDGE_STAMP, OPEN_STAMP]) {
      const spec = houseApp(options);
      expect(spec.egress, options.auth).toBe("internal");
      expect(renderQuadlet(spec), options.auth).toContain("PublishPort=127.0.0.1:3010:3010");
      expect(renderQuadlet(spec), options.auth).toContain("Network=keel-internal.network");
    }
  });

  it("refuses a client that asks for a bridge", () => {
    // Deriving around the request would be the worse failure: the entry would
    // say one thing and the deploy do another.
    for (const egress of ["internal", "open"] as const) {
      expect(() => houseApp({ ...OIDC_STAMP, egress }), egress).toThrow(/back channel/);
    }
  });
});

describe("a stamped entry is held to what a literal one is", () => {
  const stamped = houseApp(OIDC_STAMP);
  const catalog = withStamped(stamped);
  const resolved = catalogOf(catalog);

  it("closes over its roles, collides with nothing, and carries a measurable cap", () => {
    // A client with no issuer and a gated route with no gate are the two gaps
    // that fail closed and silently on the device.
    expect(deploymentGaps(resolved).errors).toEqual([]);
    // One owner per port; the same service admitting a number over TCP and UDP is one owner.
    const owners = new Map<number, string>([[22, "sshd"]]);
    for (const spec of catalog) {
      const admitted = Object.values(spec.ingress ?? {}).flatMap((set) => set ?? []);
      for (const port of [spec.port, ...admitted]) {
        expect(owners.get(port) ?? spec.name, `${port}`).toBe(spec.name);
        owners.set(port, spec.name);
      }
    }
    const names = catalog.map(subdomainOf).filter((name) => name !== null);
    expect(new Set(names).size).toBe(names.length);
    // The bounds are the budget test's own, imported rather than restated.
    const ratio = stamped.memory.max / stamped.memory.measuredMb!;
    expect(ratio).toBeGreaterThanOrEqual(CAP_HEADROOM.min);
    expect(ratio).toBeLessThanOrEqual(CAP_HEADROOM.max);
    for (const profile of PROFILES) {
      expect(priceMemory(stamped.memory, profile).maxMb).toBe(stamped.memory.max);
    }
  });

  it("renders a quadlet and a route with the properties every entry's have", () => {
    const quadlet = renderQuadlet(stamped, runSetup(stamped, HOUSE, resolved)?.env);
    expect(quadlet).toContain("Slice=keel-apps.slice");
    expect(quadlet).not.toContain("MemoryMax=");
    expect(quadlet).toContain(`EnvironmentFile=${secretsPath(stamped)}`);
    expect(quadlet).toContain("ExecStartPre=/usr/bin/mkdir -p /var/lib/atlas");
    // Field names, never values — the same check every entry's quadlet passes.
    for (const { field } of Object.values(secretFields(stamped))) {
      expect(quadlet).not.toContain(field);
    }
    const route = resolved.proxy!.role.route(stamped, {
      domain: HOUSE.network.domain,
      publicHosts: HOUSE.publicHosts,
      gate: resolved.gate,
    });
    expect(route).toContain("Host(`atlas.example.test`)");
    expect(route).toContain("- internal-only");
    expect(route).toContain("http://127.0.0.1:3010");
  });
});
