// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface AgentNetworkGuardrailModelAllowlist {
    /**
     * Whether the model allowlist check is active
     */
    enabled: boolean;
    /**
     * Allowed catalog model IDs
     */
    models: string[];
}

export interface AgentNetworkGuardrailPromptCapture {
    /**
     * Whether prompt capture is enabled for this guardrail
     */
    enabled: boolean;
    /**
     * Whether captured prompts have PII redacted
     */
    redactPii: boolean;
}

export interface AgentNetworkPolicyBudgetLimit {
    /**
     * Whether the budget limit is enforced
     */
    enabled: boolean;
    /**
     * USD allowed per source group per window (0 = uncapped)
     */
    groupCapUsd: number;
    /**
     * USD allowed per user per window (0 = uncapped)
     */
    userCapUsd: number;
    /**
     * Reset frequency in seconds (minimum 60 when enabled)
     */
    windowSeconds: number;
}

export interface AgentNetworkPolicyTokenLimit {
    /**
     * Whether the token limit is enforced
     */
    enabled: boolean;
    /**
     * Tokens allowed per source group per window (0 = uncapped)
     */
    groupCap: number;
    /**
     * Tokens allowed per individual user per window (0 = uncapped)
     */
    userCap: number;
    /**
     * Reset frequency in seconds (minimum 60 when enabled)
     */
    windowSeconds: number;
}

export interface AgentNetworkProviderModel {
    /**
     * Model identifier (e.g. `gpt-4o-mini`)
     */
    id: string;
    /**
     * Cost per 1k input tokens in USD
     */
    inputPer1k: number;
    /**
     * Cost per 1k output tokens in USD
     */
    outputPer1k: number;
}

export interface GetAgentNetworkGuardrailModelAllowlist {
    enabled: boolean;
    models: string[];
}

export interface GetAgentNetworkGuardrailPromptCapture {
    enabled: boolean;
    redactPii: boolean;
}

export interface GetAgentNetworkPolicyBudgetLimit {
    enabled: boolean;
    groupCapUsd: number;
    userCapUsd: number;
    windowSeconds: number;
}

export interface GetAgentNetworkPolicyTokenLimit {
    enabled: boolean;
    groupCap: number;
    userCap: number;
    windowSeconds: number;
}

export interface GetAgentNetworkProviderModel {
    /**
     * Model identifier
     */
    id: string;
    /**
     * Cost per 1k input tokens in USD
     */
    inputPer1k: number;
    /**
     * Cost per 1k output tokens in USD
     */
    outputPer1k: number;
}

export interface GetNameserverGroupNameserver {
    /**
     * Nameserver IP
     */
    ip: string;
    /**
     * Nameserver Type
     */
    nsType: string;
    /**
     * Nameserver Port
     */
    port: number;
}

export interface GetPolicyRule {
    /**
     * Policy Rule Action (accept|drop)
     */
    action: string;
    /**
     * Map of source group IDs to a list of local users authorized for SSH access. Keys must be group IDs present in <span pulumi-lang-nodejs="`sources`" pulumi-lang-dotnet="`Sources`" pulumi-lang-go="`sources`" pulumi-lang-python="`sources`" pulumi-lang-yaml="`sources`" pulumi-lang-java="`sources`" pulumi-lang-hcl="`sources`">`sources`</span>. If not set, all local users are permitted. Only applicable when protocol is `netbird-ssh`.
     */
    authorizedGroups: {[key: string]: string[]};
    /**
     * Policy Rule Bidirectional
     */
    bidirectional: boolean;
    /**
     * Policy description
     */
    description: string;
    /**
     * Policy Rule Destination Resource (mutually exclusive with destinations)
     */
    destinationResource: outputs.GetPolicyRuleDestinationResource;
    /**
     * Policy Rule Destination Groups (mutually exclusive with destination_resource)
     */
    destinations: string[];
    /**
     * Policy Rule Enabled
     */
    enabled: boolean;
    /**
     * Policy ID
     */
    id: string;
    /**
     * Policy Name
     */
    name: string;
    /**
     * Policy Rule Port Ranges (mutually exclusive with ports)
     */
    portRanges: outputs.GetPolicyRulePortRange[];
    /**
     * Policy Rule Ports (mutually exclusive with port_ranges)
     */
    ports: string[];
    /**
     * Policy Rule Protocol (tcp|udp|icmp|all|netbird-ssh)
     */
    protocol: string;
    /**
     * Policy Rule Source Resource (mutually exclusive with sources)
     */
    sourceResource: outputs.GetPolicyRuleSourceResource;
    /**
     * Policy Rule Source Groups (mutually exclusive with source_resource)
     */
    sources: string[];
}

export interface GetPolicyRuleDestinationResource {
    id?: string;
    type?: string;
}

export interface GetPolicyRulePortRange {
    end: number;
    start: number;
}

export interface GetPolicyRuleSourceResource {
    id?: string;
    type?: string;
}

export interface GetPostureCheckGeoLocationCheck {
    action: string;
    locations: outputs.GetPostureCheckGeoLocationCheckLocation[];
}

export interface GetPostureCheckGeoLocationCheckLocation {
    cityName: string;
    countryCode: string;
}

export interface GetPostureCheckNetbirdVersionCheck {
    minVersion: string;
}

export interface GetPostureCheckOsVersionCheck {
    androidMinVersion: string;
    darwinMinVersion: string;
    iosMinVersion: string;
    linuxMinKernelVersion: string;
    windowsMinKernelVersion: string;
}

export interface GetPostureCheckPeerNetworkRangeCheck {
    action: string;
    ranges: string[];
}

export interface GetPostureCheckProcessCheck {
    linuxPath: string;
    macPath: string;
    windowsPath: string;
}

export interface GetReverseProxyClustersCluster {
    /**
     * Cluster address used for CNAME targets
     */
    address: string;
    /**
     * Number of proxy nodes connected in this cluster
     */
    connectedProxies: number;
}

export interface GetReverseProxyServiceAccessRestrictions {
    /**
     * CIDR allowlist
     */
    allowedCidrs: string[];
    /**
     * ISO 3166-1 alpha-2 country codes to allow
     */
    allowedCountries: string[];
    /**
     * CIDR blocklist
     */
    blockedCidrs: string[];
    /**
     * ISO 3166-1 alpha-2 country codes to block
     */
    blockedCountries: string[];
}

export interface GetReverseProxyServiceAuth {
    /**
     * Bearer token authentication
     */
    bearerAuth: outputs.GetReverseProxyServiceAuthBearerAuth;
    /**
     * Static header-value authentication rules
     */
    headerAuths: outputs.GetReverseProxyServiceAuthHeaderAuth[];
    /**
     * Link authentication
     */
    linkAuth: outputs.GetReverseProxyServiceAuthLinkAuth;
    /**
     * Password authentication
     */
    passwordAuth: outputs.GetReverseProxyServiceAuthPasswordAuth;
    /**
     * PIN authentication
     */
    pinAuth: outputs.GetReverseProxyServiceAuthPinAuth;
}

export interface GetReverseProxyServiceAuthBearerAuth {
    /**
     * List of group IDs that can use bearer auth
     */
    distributionGroups: string[];
    enabled: boolean;
}

export interface GetReverseProxyServiceAuthHeaderAuth {
    enabled: boolean;
    /**
     * HTTP header name to check
     */
    header: string;
    /**
     * Expected header value
     */
    value: string;
}

export interface GetReverseProxyServiceAuthLinkAuth {
    enabled: boolean;
}

export interface GetReverseProxyServiceAuthPasswordAuth {
    enabled: boolean;
    password: string;
}

export interface GetReverseProxyServiceAuthPinAuth {
    enabled: boolean;
    pin: string;
}

export interface GetReverseProxyServiceTarget {
    /**
     * Whether this target is enabled
     */
    enabled: boolean;
    /**
     * Backend IP or domain for this target
     */
    host: string;
    /**
     * Per-target options
     */
    options: outputs.GetReverseProxyServiceTargetOptions;
    /**
     * URL path prefix for this target
     */
    path: string;
    /**
     * Backend port for this target
     */
    port: number;
    /**
     * Protocol to use when connecting to the backend (http, https for HTTP mode; tcp, udp for L4 mode)
     */
    protocol: string;
    /**
     * Target ID (resource or peer ID)
     */
    targetId: string;
    /**
     * Target type (peer, host, domain, subnet)
     */
    targetType: string;
}

export interface GetReverseProxyServiceTargetOptions {
    /**
     * Extra headers sent to the backend (HTTP only). Marked sensitive since values commonly carry credentials, e.g. an `Authorization` header.
     */
    customHeaders: {[key: string]: string};
    /**
     * Controls how the request path is rewritten before forwarding (HTTP only)
     */
    pathRewrite: string;
    /**
     * Send PROXY Protocol v2 header to this backend (TCP/TLS only)
     */
    proxyProtocol: boolean;
    /**
     * Per-target response timeout as a Go duration string
     */
    requestTimeout: string;
    /**
     * Idle timeout before a UDP session is reaped (UDP only)
     */
    sessionIdleTimeout: string;
    /**
     * Skip TLS certificate verification for this backend (HTTPS targets only)
     */
    skipTlsVerify: boolean;
}

export interface NameserverGroupNameserver {
    /**
     * Nameserver IP
     */
    ip: string;
    /**
     * Nameserver Type
     */
    nsType: string;
    /**
     * Nameserver Port
     */
    port: number;
}

export interface PolicyRule {
    /**
     * Policy Rule Action (accept|drop)
     */
    action: string;
    /**
     * Map of source group IDs to a list of local users authorized for SSH access. Keys must be group IDs present in <span pulumi-lang-nodejs="`sources`" pulumi-lang-dotnet="`Sources`" pulumi-lang-go="`sources`" pulumi-lang-python="`sources`" pulumi-lang-yaml="`sources`" pulumi-lang-java="`sources`" pulumi-lang-hcl="`sources`">`sources`</span>. If not set, all local users are permitted. Only applicable when protocol is `netbird-ssh`.
     */
    authorizedGroups: {[key: string]: string[]};
    /**
     * Policy Rule Bidirectional
     */
    bidirectional: boolean;
    /**
     * Policy description
     */
    description?: string;
    /**
     * Policy Rule Destination Resource (mutually exclusive with destinations)
     */
    destinationResource: outputs.PolicyRuleDestinationResource;
    /**
     * Policy Rule Destination Groups (mutually exclusive with destination_resource)
     */
    destinations: string[];
    /**
     * Policy Rule Enabled
     */
    enabled: boolean;
    /**
     * Policy ID
     */
    id: string;
    /**
     * Policy Name
     */
    name: string;
    /**
     * Policy Rule Port Ranges (mutually exclusive with ports)
     */
    portRanges: outputs.PolicyRulePortRange[];
    /**
     * Policy Rule Ports (mutually exclusive with port_ranges)
     */
    ports: string[];
    /**
     * Policy Rule Protocol (tcp|udp|icmp|all|netbird-ssh)
     */
    protocol: string;
    /**
     * Policy Rule Source Resource (mutually exclusive with sources)
     */
    sourceResource: outputs.PolicyRuleSourceResource;
    /**
     * Policy Rule Source Groups (mutually exclusive with source_resource)
     */
    sources: string[];
}

export interface PolicyRuleDestinationResource {
    id?: string;
    type?: string;
}

export interface PolicyRulePortRange {
    end: number;
    start: number;
}

export interface PolicyRuleSourceResource {
    id?: string;
    type?: string;
}

export interface PostureCheckGeoLocationCheck {
    action?: string;
    locations?: outputs.PostureCheckGeoLocationCheckLocation[];
}

export interface PostureCheckGeoLocationCheckLocation {
    cityName?: string;
    countryCode: string;
}

export interface PostureCheckNetbirdVersionCheck {
    minVersion?: string;
}

export interface PostureCheckOsVersionCheck {
    androidMinVersion?: string;
    darwinMinVersion?: string;
    iosMinVersion?: string;
    linuxMinKernelVersion?: string;
    windowsMinKernelVersion?: string;
}

export interface PostureCheckPeerNetworkRangeCheck {
    action?: string;
    ranges?: string[];
}

export interface PostureCheckProcessCheck {
    linuxPath?: string;
    macPath?: string;
    windowsPath?: string;
}

export interface ReverseProxyServiceAccessRestrictions {
    /**
     * CIDR allowlist
     */
    allowedCidrs?: string[];
    /**
     * ISO 3166-1 alpha-2 country codes to allow
     */
    allowedCountries?: string[];
    /**
     * CIDR blocklist
     */
    blockedCidrs?: string[];
    /**
     * ISO 3166-1 alpha-2 country codes to block
     */
    blockedCountries?: string[];
}

export interface ReverseProxyServiceAuth {
    /**
     * Bearer token authentication
     */
    bearerAuth?: outputs.ReverseProxyServiceAuthBearerAuth;
    /**
     * Static header-value authentication rules
     */
    headerAuths?: outputs.ReverseProxyServiceAuthHeaderAuth[];
    /**
     * Link authentication
     */
    linkAuth?: outputs.ReverseProxyServiceAuthLinkAuth;
    /**
     * Password authentication
     */
    passwordAuth?: outputs.ReverseProxyServiceAuthPasswordAuth;
    /**
     * PIN authentication
     */
    pinAuth?: outputs.ReverseProxyServiceAuthPinAuth;
}

export interface ReverseProxyServiceAuthBearerAuth {
    /**
     * List of group IDs that can use bearer auth
     */
    distributionGroups?: string[];
    enabled: boolean;
}

export interface ReverseProxyServiceAuthHeaderAuth {
    enabled: boolean;
    /**
     * HTTP header name to check
     */
    header: string;
    /**
     * Expected header value
     */
    value: string;
}

export interface ReverseProxyServiceAuthLinkAuth {
    enabled: boolean;
}

export interface ReverseProxyServiceAuthPasswordAuth {
    enabled: boolean;
    password?: string;
}

export interface ReverseProxyServiceAuthPinAuth {
    enabled: boolean;
    pin?: string;
}

export interface ReverseProxyServiceTarget {
    /**
     * Whether this target is enabled
     */
    enabled: boolean;
    /**
     * Backend IP or domain for this target. If omitted, the API resolves it from the target peer.
     */
    host: string;
    /**
     * Per-target options
     */
    options?: outputs.ReverseProxyServiceTargetOptions;
    /**
     * URL path prefix for this target. Defaults to "/" if omitted.
     */
    path: string;
    /**
     * Backend port for this target (0 for scheme default)
     */
    port: number;
    /**
     * Protocol to use when connecting to the backend (http, https for HTTP mode; tcp, udp for L4 mode)
     */
    protocol: string;
    /**
     * Target ID (resource or peer ID)
     */
    targetId: string;
    /**
     * Target type (peer, host, domain, subnet)
     */
    targetType: string;
}

export interface ReverseProxyServiceTargetOptions {
    /**
     * Extra headers sent to the backend (HTTP only). Marked sensitive since values commonly carry credentials, e.g. an `Authorization` header.
     */
    customHeaders?: {[key: string]: string};
    /**
     * Controls how the request path is rewritten before forwarding. Default strips the matched prefix. "preserve" keeps the full original path. (HTTP only)
     */
    pathRewrite?: string;
    /**
     * Send PROXY Protocol v2 header to this backend (TCP/TLS only)
     */
    proxyProtocol?: boolean;
    /**
     * Per-target response timeout as a Go duration string (e.g. "30s", "2m")
     */
    requestTimeout?: string;
    /**
     * Idle timeout before a UDP session is reaped, as a Go duration string (e.g. "30s", "2m"). Maximum 10m. (UDP only)
     */
    sessionIdleTimeout?: string;
    /**
     * Skip TLS certificate verification for this backend (HTTPS targets only)
     */
    skipTlsVerify?: boolean;
}

