/**
 * Text the program composed, sealed for one host.
 *
 * `SealedEnv`'s sibling, and the whole difference is where the plaintext comes
 * from. There it is read out of the vault inside the provider, so it exists only
 * for the length of a call. Here it is a value the program built — a server's
 * configuration with generated key material in it — so it arrives as an input.
 *
 * **An input marked `pulumi.secret()` is not a captured value.** The rule a
 * dynamic provider lives under is that a closure must never *capture* a secret:
 * the serialiser writes captured values into state as plaintext
 * (pulumi/pulumi#8265), and nothing about that is encrypted. An input is a
 * different mechanism — the engine encrypts it with the stack's secret provider
 * before the checkpoint is written and decrypts it again for the provider's own
 * call — so what the state file holds is ciphertext under the stack passphrase.
 * This is the one place in the repository where a secret value is in Pulumi
 * state at all: everything read from the vault is sealed for the board before it
 * becomes anything Pulumi carries, and everything generated by a provider is
 * sealed inside the call that makes it.
 *
 * The outputs are the age blob and a hash of the plaintext, exactly as
 * `SealedEnv`'s are: `SecretFile` diffs on the hash because age is not
 * deterministic, and the service's restart trigger folds it in, so a regenerated
 * value restarts the service that reads it.
 *
 * No `read`. There is nothing external to ask — the plaintext is the program's
 * own value, and a refresh has no other source of truth to compare it against.
 * What can drift is the blob on the device, which is `SecretFile`'s to check and
 * does.
 */

import * as pulumi from "@pulumi/pulumi";

import { hash, seal } from "../age";
import { type Args } from "./inputs";

export type SealedTextInputs = {
  /**
   * The file's body. Marked `pulumi.secret()` by the caller, which is what puts
   * it in the checkpoint encrypted rather than in the clear.
   */
  plaintext: string;
  /**
   * Public half of the age identity on the target host. Not a secret: it only
   * lets you encrypt *to* the host.
   */
  ageRecipient: string;
};

/**
 * The plaintext is deliberately not among them. It is an input and stays one:
 * an output would be a second copy of the same value, carried under whatever
 * secretness the engine inferred for it rather than the one the caller asked
 * for.
 */
type Outs = {
  ageRecipient: string;
  /** age ciphertext. Safe in state; the identity that opens it is on the host. */
  ciphertext: string;
  /** sha256 of the plaintext. What a regeneration is detected by. */
  plaintextHash: string;
};

const provider: pulumi.dynamic.ResourceProvider<SealedTextInputs, Outs> = {
  async create(inputs) {
    const sealed = await seal(inputs.plaintext, inputs.ageRecipient);
    // The fingerprint of what was sealed first. Nothing on a device is keyed by
    // it — the URN is what identifies this resource — and a dynamic resource's
    // id cannot be restated by an update, so it says what it can and no more.
    return { id: sealed.plaintextHash, outs: { ageRecipient: inputs.ageRecipient, ...sealed } };
  },

  async check(_olds, news) {
    const failures: pulumi.dynamic.CheckFailure[] = [];
    if (!news.ageRecipient.startsWith("age1")) {
      failures.push({ property: "ageRecipient", reason: "not an age recipient" });
    }
    // An unknown that slipped through dependency resolution arrives as an empty
    // string, and an empty body is a service that starts with no configuration
    // at all — a boot-time mystery rather than a deploy-time error.
    if (news.plaintext === "") {
      failures.push({ property: "plaintext", reason: "refusing to seal an empty body" });
    }
    return { inputs: news, failures };
  },

  async diff(_id, olds, news) {
    // On the hash and never on the ciphertext: age is not deterministic, so
    // comparing blobs would report a change on every run and restart the service
    // every deploy.
    const plaintextHash = await hash(news.plaintext);
    return {
      changes: olds.ageRecipient !== news.ageRecipient || olds.plaintextHash !== plaintextHash,
    };
  },

  async update(_id, _olds, news) {
    const sealed = await seal(news.plaintext, news.ageRecipient);
    return { outs: { ageRecipient: news.ageRecipient, ...sealed } };
  },

  // No `delete`: this resource owns nothing outside the checkpoint. The blob on
  // the device belongs to `SecretFile`, whose delete removes it and the
  // decrypted sibling with it.
};

export class SealedText extends pulumi.dynamic.Resource {
  declare public readonly ciphertext: pulumi.Output<string>;
  declare public readonly plaintextHash: pulumi.Output<string>;

  constructor(name: string, args: Args<SealedTextInputs>, opts?: pulumi.CustomResourceOptions) {
    super(provider, name, { ...args, ciphertext: undefined, plaintextHash: undefined }, opts);
  }
}
