// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class AgentNetworkPolicy extends pulumi.CustomResource {
    /**
     * Get an existing AgentNetworkPolicy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AgentNetworkPolicyState, opts?: pulumi.CustomResourceOptions): AgentNetworkPolicy {
        return new AgentNetworkPolicy(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netbird:index/agentNetworkPolicy:AgentNetworkPolicy';

    /**
     * Returns true if the given object is an instance of AgentNetworkPolicy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AgentNetworkPolicy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AgentNetworkPolicy.__pulumiType;
    }

    /**
     * Per-policy USD spend cap
     */
    declare public readonly budgetLimit: pulumi.Output<outputs.AgentNetworkPolicyBudgetLimit>;
    /**
     * Optional human-readable description
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Agent Network provider IDs the source groups can reach. Must contain at least one non-empty provider ID.
     */
    declare public readonly destinationProviderIds: pulumi.Output<string[]>;
    /**
     * Whether the policy is enabled
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * Agent Network guardrail IDs attached to this policy
     */
    declare public readonly guardrailIds: pulumi.Output<string[]>;
    /**
     * Display name for the policy
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * NetBird group IDs whose members may call the destination providers. Must contain at least one non-empty group ID.
     */
    declare public readonly sourceGroups: pulumi.Output<string[]>;
    /**
     * Per-policy token cap
     */
    declare public readonly tokenLimit: pulumi.Output<outputs.AgentNetworkPolicyTokenLimit>;

    /**
     * Create a AgentNetworkPolicy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AgentNetworkPolicyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AgentNetworkPolicyArgs | AgentNetworkPolicyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AgentNetworkPolicyState | undefined;
            resourceInputs["budgetLimit"] = state?.budgetLimit;
            resourceInputs["description"] = state?.description;
            resourceInputs["destinationProviderIds"] = state?.destinationProviderIds;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["guardrailIds"] = state?.guardrailIds;
            resourceInputs["name"] = state?.name;
            resourceInputs["sourceGroups"] = state?.sourceGroups;
            resourceInputs["tokenLimit"] = state?.tokenLimit;
        } else {
            const args = argsOrState as AgentNetworkPolicyArgs | undefined;
            if (args?.destinationProviderIds === undefined && !opts.urn) {
                throw new Error("Missing required property 'destinationProviderIds'");
            }
            if (args?.sourceGroups === undefined && !opts.urn) {
                throw new Error("Missing required property 'sourceGroups'");
            }
            resourceInputs["budgetLimit"] = args?.budgetLimit;
            resourceInputs["description"] = args?.description;
            resourceInputs["destinationProviderIds"] = args?.destinationProviderIds;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["guardrailIds"] = args?.guardrailIds;
            resourceInputs["name"] = args?.name;
            resourceInputs["sourceGroups"] = args?.sourceGroups;
            resourceInputs["tokenLimit"] = args?.tokenLimit;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AgentNetworkPolicy.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering AgentNetworkPolicy resources.
 */
export interface AgentNetworkPolicyState {
    /**
     * Per-policy USD spend cap
     */
    budgetLimit?: pulumi.Input<inputs.AgentNetworkPolicyBudgetLimit | undefined>;
    /**
     * Optional human-readable description
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Agent Network provider IDs the source groups can reach. Must contain at least one non-empty provider ID.
     */
    destinationProviderIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Whether the policy is enabled
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Agent Network guardrail IDs attached to this policy
     */
    guardrailIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Display name for the policy
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * NetBird group IDs whose members may call the destination providers. Must contain at least one non-empty group ID.
     */
    sourceGroups?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Per-policy token cap
     */
    tokenLimit?: pulumi.Input<inputs.AgentNetworkPolicyTokenLimit | undefined>;
}

/**
 * The set of arguments for constructing a AgentNetworkPolicy resource.
 */
export interface AgentNetworkPolicyArgs {
    /**
     * Per-policy USD spend cap
     */
    budgetLimit?: pulumi.Input<inputs.AgentNetworkPolicyBudgetLimit | undefined>;
    /**
     * Optional human-readable description
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Agent Network provider IDs the source groups can reach. Must contain at least one non-empty provider ID.
     */
    destinationProviderIds: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Whether the policy is enabled
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Agent Network guardrail IDs attached to this policy
     */
    guardrailIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Display name for the policy
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * NetBird group IDs whose members may call the destination providers. Must contain at least one non-empty group ID.
     */
    sourceGroups: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Per-policy token cap
     */
    tokenLimit?: pulumi.Input<inputs.AgentNetworkPolicyTokenLimit | undefined>;
}
