// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class AgentNetworkGuardrail extends pulumi.CustomResource {
    /**
     * Get an existing AgentNetworkGuardrail resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AgentNetworkGuardrailState, opts?: pulumi.CustomResourceOptions): AgentNetworkGuardrail {
        return new AgentNetworkGuardrail(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netbird:index/agentNetworkGuardrail:AgentNetworkGuardrail';

    /**
     * Returns true if the given object is an instance of AgentNetworkGuardrail.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AgentNetworkGuardrail {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AgentNetworkGuardrail.__pulumiType;
    }

    /**
     * Optional human-readable description
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Restrict which catalog models are allowed
     */
    declare public readonly modelAllowlist: pulumi.Output<outputs.AgentNetworkGuardrailModelAllowlist>;
    /**
     * Display name for the guardrail
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Request/response prompt capture settings
     */
    declare public readonly promptCapture: pulumi.Output<outputs.AgentNetworkGuardrailPromptCapture>;

    /**
     * Create a AgentNetworkGuardrail resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AgentNetworkGuardrailArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AgentNetworkGuardrailArgs | AgentNetworkGuardrailState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AgentNetworkGuardrailState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["modelAllowlist"] = state?.modelAllowlist;
            resourceInputs["name"] = state?.name;
            resourceInputs["promptCapture"] = state?.promptCapture;
        } else {
            const args = argsOrState as AgentNetworkGuardrailArgs | undefined;
            if (args?.modelAllowlist === undefined && !opts.urn) {
                throw new Error("Missing required property 'modelAllowlist'");
            }
            if (args?.promptCapture === undefined && !opts.urn) {
                throw new Error("Missing required property 'promptCapture'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["modelAllowlist"] = args?.modelAllowlist;
            resourceInputs["name"] = args?.name;
            resourceInputs["promptCapture"] = args?.promptCapture;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AgentNetworkGuardrail.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering AgentNetworkGuardrail resources.
 */
export interface AgentNetworkGuardrailState {
    /**
     * Optional human-readable description
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Restrict which catalog models are allowed
     */
    modelAllowlist?: pulumi.Input<inputs.AgentNetworkGuardrailModelAllowlist | undefined>;
    /**
     * Display name for the guardrail
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Request/response prompt capture settings
     */
    promptCapture?: pulumi.Input<inputs.AgentNetworkGuardrailPromptCapture | undefined>;
}

/**
 * The set of arguments for constructing a AgentNetworkGuardrail resource.
 */
export interface AgentNetworkGuardrailArgs {
    /**
     * Optional human-readable description
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Restrict which catalog models are allowed
     */
    modelAllowlist: pulumi.Input<inputs.AgentNetworkGuardrailModelAllowlist>;
    /**
     * Display name for the guardrail
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Request/response prompt capture settings
     */
    promptCapture: pulumi.Input<inputs.AgentNetworkGuardrailPromptCapture>;
}
