// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class DnsRecord extends pulumi.CustomResource {
    /**
     * Get an existing DnsRecord resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DnsRecordState, opts?: pulumi.CustomResourceOptions): DnsRecord {
        return new DnsRecord(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netbird:index/dnsRecord:DnsRecord';

    /**
     * Returns true if the given object is an instance of DnsRecord.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DnsRecord {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DnsRecord.__pulumiType;
    }

    /**
     * DNS record content (IP address for A/AAAA, domain for CNAME)
     */
    declare public readonly content: pulumi.Output<string>;
    /**
     * DNS record name as a full FQDN (e.g., 'www.example.com' or 'example.com' for root domain). Short names like 'www' or '@' are not supported
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Time to live in seconds
     */
    declare public readonly ttl: pulumi.Output<number>;
    /**
     * DNS record type (A, AAAA, or CNAME)
     */
    declare public readonly type: pulumi.Output<string>;
    /**
     * DNS Zone ID that this record belongs to
     */
    declare public readonly zoneId: pulumi.Output<string>;

    /**
     * Create a DnsRecord resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DnsRecordArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DnsRecordArgs | DnsRecordState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DnsRecordState | undefined;
            resourceInputs["content"] = state?.content;
            resourceInputs["name"] = state?.name;
            resourceInputs["ttl"] = state?.ttl;
            resourceInputs["type"] = state?.type;
            resourceInputs["zoneId"] = state?.zoneId;
        } else {
            const args = argsOrState as DnsRecordArgs | undefined;
            if (args?.content === undefined && !opts.urn) {
                throw new Error("Missing required property 'content'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            if (args?.zoneId === undefined && !opts.urn) {
                throw new Error("Missing required property 'zoneId'");
            }
            resourceInputs["content"] = args?.content;
            resourceInputs["name"] = args?.name;
            resourceInputs["ttl"] = args?.ttl;
            resourceInputs["type"] = args?.type;
            resourceInputs["zoneId"] = args?.zoneId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DnsRecord.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering DnsRecord resources.
 */
export interface DnsRecordState {
    /**
     * DNS record content (IP address for A/AAAA, domain for CNAME)
     */
    content?: pulumi.Input<string | undefined>;
    /**
     * DNS record name as a full FQDN (e.g., 'www.example.com' or 'example.com' for root domain). Short names like 'www' or '@' are not supported
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Time to live in seconds
     */
    ttl?: pulumi.Input<number | undefined>;
    /**
     * DNS record type (A, AAAA, or CNAME)
     */
    type?: pulumi.Input<string | undefined>;
    /**
     * DNS Zone ID that this record belongs to
     */
    zoneId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a DnsRecord resource.
 */
export interface DnsRecordArgs {
    /**
     * DNS record content (IP address for A/AAAA, domain for CNAME)
     */
    content: pulumi.Input<string>;
    /**
     * DNS record name as a full FQDN (e.g., 'www.example.com' or 'example.com' for root domain). Short names like 'www' or '@' are not supported
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Time to live in seconds
     */
    ttl?: pulumi.Input<number | undefined>;
    /**
     * DNS record type (A, AAAA, or CNAME)
     */
    type: pulumi.Input<string>;
    /**
     * DNS Zone ID that this record belongs to
     */
    zoneId: pulumi.Input<string>;
}
