// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class DnsSettings extends pulumi.CustomResource {
    /**
     * Get an existing DnsSettings resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DnsSettingsState, opts?: pulumi.CustomResourceOptions): DnsSettings {
        return new DnsSettings(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netbird:index/dnsSettings:DnsSettings';

    /**
     * Returns true if the given object is an instance of DnsSettings.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DnsSettings {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DnsSettings.__pulumiType;
    }

    /**
     * Groups whose DNS management is disabled
     */
    declare public readonly disabledManagementGroups: pulumi.Output<string[]>;

    /**
     * Create a DnsSettings resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DnsSettingsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DnsSettingsArgs | DnsSettingsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DnsSettingsState | undefined;
            resourceInputs["disabledManagementGroups"] = state?.disabledManagementGroups;
        } else {
            const args = argsOrState as DnsSettingsArgs | undefined;
            if (args?.disabledManagementGroups === undefined && !opts.urn) {
                throw new Error("Missing required property 'disabledManagementGroups'");
            }
            resourceInputs["disabledManagementGroups"] = args?.disabledManagementGroups;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DnsSettings.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering DnsSettings resources.
 */
export interface DnsSettingsState {
    /**
     * Groups whose DNS management is disabled
     */
    disabledManagementGroups?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

/**
 * The set of arguments for constructing a DnsSettings resource.
 */
export interface DnsSettingsArgs {
    /**
     * Groups whose DNS management is disabled
     */
    disabledManagementGroups: pulumi.Input<pulumi.Input<string>[]>;
}
