// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class DnsZone extends pulumi.CustomResource {
    /**
     * Get an existing DnsZone resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DnsZoneState, opts?: pulumi.CustomResourceOptions): DnsZone {
        return new DnsZone(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netbird:index/dnsZone:DnsZone';

    /**
     * Returns true if the given object is an instance of DnsZone.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DnsZone {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DnsZone.__pulumiType;
    }

    /**
     * Group IDs that define groups of peers that will resolve this zone
     */
    declare public readonly distributionGroups: pulumi.Output<string[]>;
    /**
     * Zone domain (FQDN)
     */
    declare public readonly domain: pulumi.Output<string>;
    /**
     * Enable this zone as a search domain
     */
    declare public readonly enableSearchDomain: pulumi.Output<boolean>;
    /**
     * DNS Zone status
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * DNS Zone name identifier
     */
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a DnsZone resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DnsZoneArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DnsZoneArgs | DnsZoneState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DnsZoneState | undefined;
            resourceInputs["distributionGroups"] = state?.distributionGroups;
            resourceInputs["domain"] = state?.domain;
            resourceInputs["enableSearchDomain"] = state?.enableSearchDomain;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as DnsZoneArgs | undefined;
            if (args?.domain === undefined && !opts.urn) {
                throw new Error("Missing required property 'domain'");
            }
            resourceInputs["distributionGroups"] = args?.distributionGroups;
            resourceInputs["domain"] = args?.domain;
            resourceInputs["enableSearchDomain"] = args?.enableSearchDomain;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["name"] = args?.name;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DnsZone.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering DnsZone resources.
 */
export interface DnsZoneState {
    /**
     * Group IDs that define groups of peers that will resolve this zone
     */
    distributionGroups?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Zone domain (FQDN)
     */
    domain?: pulumi.Input<string | undefined>;
    /**
     * Enable this zone as a search domain
     */
    enableSearchDomain?: pulumi.Input<boolean | undefined>;
    /**
     * DNS Zone status
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * DNS Zone name identifier
     */
    name?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a DnsZone resource.
 */
export interface DnsZoneArgs {
    /**
     * Group IDs that define groups of peers that will resolve this zone
     */
    distributionGroups?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Zone domain (FQDN)
     */
    domain: pulumi.Input<string>;
    /**
     * Enable this zone as a search domain
     */
    enableSearchDomain?: pulumi.Input<boolean | undefined>;
    /**
     * DNS Zone status
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * DNS Zone name identifier
     */
    name?: pulumi.Input<string | undefined>;
}
