// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getAgentNetworkProvider(args?: GetAgentNetworkProviderArgs, opts?: pulumi.InvokeOptions): Promise<GetAgentNetworkProviderResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netbird:index/getAgentNetworkProvider:getAgentNetworkProvider", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAgentNetworkProvider.
 */
export interface GetAgentNetworkProviderArgs {
    id?: string;
    name?: string;
}

/**
 * A collection of values returned by getAgentNetworkProvider.
 */
export interface GetAgentNetworkProviderResult {
    readonly apiKey: string;
    readonly enabled: boolean;
    readonly extraValues: {[key: string]: string};
    readonly id: string;
    readonly identityHeaderGroups: string;
    readonly identityHeaderUserId: string;
    readonly metadataDisabled: boolean;
    readonly models: outputs.GetAgentNetworkProviderModel[];
    readonly name: string;
    readonly providerId: string;
    readonly skipTlsVerification: boolean;
    readonly upstreamUrl: string;
}
export function getAgentNetworkProviderOutput(args?: GetAgentNetworkProviderOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAgentNetworkProviderResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netbird:index/getAgentNetworkProvider:getAgentNetworkProvider", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAgentNetworkProvider.
 */
export interface GetAgentNetworkProviderOutputArgs {
    id?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
}
