// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getAgentNetworkPolicy(args?: GetAgentNetworkPolicyArgs, opts?: pulumi.InvokeOptions): Promise<GetAgentNetworkPolicyResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netbird:index/getAgentNetworkPolicy:getAgentNetworkPolicy", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAgentNetworkPolicy.
 */
export interface GetAgentNetworkPolicyArgs {
    id?: string;
    name?: string;
}

/**
 * A collection of values returned by getAgentNetworkPolicy.
 */
export interface GetAgentNetworkPolicyResult {
    readonly budgetLimit: outputs.GetAgentNetworkPolicyBudgetLimit;
    readonly description: string;
    readonly destinationProviderIds: string[];
    readonly enabled: boolean;
    readonly guardrailIds: string[];
    readonly id: string;
    readonly name: string;
    readonly sourceGroups: string[];
    readonly tokenLimit: outputs.GetAgentNetworkPolicyTokenLimit;
}
export function getAgentNetworkPolicyOutput(args?: GetAgentNetworkPolicyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAgentNetworkPolicyResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netbird:index/getAgentNetworkPolicy:getAgentNetworkPolicy", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAgentNetworkPolicy.
 */
export interface GetAgentNetworkPolicyOutputArgs {
    id?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
}
