// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getAccountSettings(opts?: pulumi.InvokeOptions): Promise<GetAccountSettingsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netbird:index/getAccountSettings:getAccountSettings", {
    }, opts, utilities.getPackage());
}

/**
 * A collection of values returned by getAccountSettings.
 */
export interface GetAccountSettingsResult {
    readonly autoUpdateVersion: string;
    readonly dnsDomain: string;
    readonly groupsPropagationEnabled: boolean;
    readonly id: string;
    readonly jwtAllowGroups: string[];
    readonly jwtGroupsClaimName: string;
    readonly jwtGroupsEnabled: boolean;
    readonly lazyConnectionEnabled: boolean;
    readonly networkRange: string;
    readonly networkTrafficLogsEnabled: boolean;
    readonly networkTrafficLogsGroups: string[];
    readonly networkTrafficPacketCounterEnabled: boolean;
    readonly peerApprovalEnabled: boolean;
    readonly peerExposeEnabled: boolean;
    readonly peerExposeGroups: string[];
    readonly peerInactivityExpiration: number;
    readonly peerInactivityExpirationEnabled: boolean;
    readonly peerLoginExpiration: number;
    readonly peerLoginExpirationEnabled: boolean;
    readonly regularUsersViewBlocked: boolean;
    readonly routingPeerDnsResolutionEnabled: boolean;
    readonly userApprovalRequired: boolean;
}
export function getAccountSettingsOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAccountSettingsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netbird:index/getAccountSettings:getAccountSettings", {
    }, opts, utilities.getPackage());
}
