// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getAgentNetworkGuardrail(args?: GetAgentNetworkGuardrailArgs, opts?: pulumi.InvokeOptions): Promise<GetAgentNetworkGuardrailResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netbird:index/getAgentNetworkGuardrail:getAgentNetworkGuardrail", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAgentNetworkGuardrail.
 */
export interface GetAgentNetworkGuardrailArgs {
    id?: string;
    name?: string;
}

/**
 * A collection of values returned by getAgentNetworkGuardrail.
 */
export interface GetAgentNetworkGuardrailResult {
    readonly description: string;
    readonly id: string;
    readonly modelAllowlist: outputs.GetAgentNetworkGuardrailModelAllowlist;
    readonly name: string;
    readonly promptCapture: outputs.GetAgentNetworkGuardrailPromptCapture;
}
export function getAgentNetworkGuardrailOutput(args?: GetAgentNetworkGuardrailOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAgentNetworkGuardrailResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netbird:index/getAgentNetworkGuardrail:getAgentNetworkGuardrail", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAgentNetworkGuardrail.
 */
export interface GetAgentNetworkGuardrailOutputArgs {
    id?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
}
