// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getDnsSettings(opts?: pulumi.InvokeOptions): Promise<GetDnsSettingsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netbird:index/getDnsSettings:getDnsSettings", {
    }, opts, utilities.getPackage());
}

/**
 * A collection of values returned by getDnsSettings.
 */
export interface GetDnsSettingsResult {
    readonly disabledManagementGroups: string[];
}
export function getDnsSettingsOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetDnsSettingsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netbird:index/getDnsSettings:getDnsSettings", {
    }, opts, utilities.getPackage());
}
