// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getDnsRecord(args: GetDnsRecordArgs, opts?: pulumi.InvokeOptions): Promise<GetDnsRecordResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netbird:index/getDnsRecord:getDnsRecord", {
        "id": args.id,
        "name": args.name,
        "type": args.type,
        "zoneId": args.zoneId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getDnsRecord.
 */
export interface GetDnsRecordArgs {
    id?: string;
    name?: string;
    type?: string;
    zoneId: string;
}

/**
 * A collection of values returned by getDnsRecord.
 */
export interface GetDnsRecordResult {
    readonly content: string;
    readonly id: string;
    readonly name: string;
    readonly ttl: number;
    readonly type: string;
    readonly zoneId: string;
}
export function getDnsRecordOutput(args: GetDnsRecordOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetDnsRecordResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netbird:index/getDnsRecord:getDnsRecord", {
        "id": args.id,
        "name": args.name,
        "type": args.type,
        "zoneId": args.zoneId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getDnsRecord.
 */
export interface GetDnsRecordOutputArgs {
    id?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
    type?: pulumi.Input<string | undefined>;
    zoneId: pulumi.Input<string>;
}
