// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getNetworkResource(args: GetNetworkResourceArgs, opts?: pulumi.InvokeOptions): Promise<GetNetworkResourceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netbird:index/getNetworkResource:getNetworkResource", {
        "id": args.id,
        "name": args.name,
        "networkId": args.networkId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getNetworkResource.
 */
export interface GetNetworkResourceArgs {
    id?: string;
    name?: string;
    networkId: string;
}

/**
 * A collection of values returned by getNetworkResource.
 */
export interface GetNetworkResourceResult {
    readonly address: string;
    readonly description: string;
    readonly enabled: boolean;
    readonly groups: string[];
    readonly id: string;
    readonly name: string;
    readonly networkId: string;
}
export function getNetworkResourceOutput(args: GetNetworkResourceOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetNetworkResourceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netbird:index/getNetworkResource:getNetworkResource", {
        "id": args.id,
        "name": args.name,
        "networkId": args.networkId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getNetworkResource.
 */
export interface GetNetworkResourceOutputArgs {
    id?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
    networkId: pulumi.Input<string>;
}
