// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getNameserverGroup(args?: GetNameserverGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetNameserverGroupResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netbird:index/getNameserverGroup:getNameserverGroup", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getNameserverGroup.
 */
export interface GetNameserverGroupArgs {
    id?: string;
    name?: string;
}

/**
 * A collection of values returned by getNameserverGroup.
 */
export interface GetNameserverGroupResult {
    readonly description: string;
    readonly domains: string[];
    readonly enabled: boolean;
    readonly groups: string[];
    readonly id: string;
    readonly name: string;
    readonly nameservers: outputs.GetNameserverGroupNameserver[];
    readonly primary: boolean;
    readonly searchDomainsEnabled: boolean;
}
export function getNameserverGroupOutput(args?: GetNameserverGroupOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetNameserverGroupResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netbird:index/getNameserverGroup:getNameserverGroup", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getNameserverGroup.
 */
export interface GetNameserverGroupOutputArgs {
    id?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
}
