// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getNetworkRouter(args: GetNetworkRouterArgs, opts?: pulumi.InvokeOptions): Promise<GetNetworkRouterResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netbird:index/getNetworkRouter:getNetworkRouter", {
        "id": args.id,
        "networkId": args.networkId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getNetworkRouter.
 */
export interface GetNetworkRouterArgs {
    id: string;
    networkId: string;
}

/**
 * A collection of values returned by getNetworkRouter.
 */
export interface GetNetworkRouterResult {
    readonly enabled: boolean;
    readonly id: string;
    readonly masquerade: boolean;
    readonly metric: number;
    readonly networkId: string;
    readonly peer: string;
    readonly peerGroups: string[];
}
export function getNetworkRouterOutput(args: GetNetworkRouterOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetNetworkRouterResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netbird:index/getNetworkRouter:getNetworkRouter", {
        "id": args.id,
        "networkId": args.networkId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getNetworkRouter.
 */
export interface GetNetworkRouterOutputArgs {
    id: pulumi.Input<string>;
    networkId: pulumi.Input<string>;
}
