// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getPeers(args?: GetPeersArgs, opts?: pulumi.InvokeOptions): Promise<GetPeersResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netbird:index/getPeers:getPeers", {
        "approvalRequired": args.approvalRequired,
        "cityName": args.cityName,
        "connected": args.connected,
        "connectionIp": args.connectionIp,
        "countryCode": args.countryCode,
        "dnsLabel": args.dnsLabel,
        "extraDnsLabels": args.extraDnsLabels,
        "geonameId": args.geonameId,
        "groups": args.groups,
        "hostname": args.hostname,
        "inactivityExpirationEnabled": args.inactivityExpirationEnabled,
        "ip": args.ip,
        "loginExpirationEnabled": args.loginExpirationEnabled,
        "loginExpired": args.loginExpired,
        "name": args.name,
        "os": args.os,
        "sshEnabled": args.sshEnabled,
        "userId": args.userId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPeers.
 */
export interface GetPeersArgs {
    approvalRequired?: boolean;
    cityName?: string;
    connected?: boolean;
    connectionIp?: string;
    countryCode?: string;
    dnsLabel?: string;
    extraDnsLabels?: string[];
    geonameId?: number;
    groups?: string[];
    hostname?: string;
    inactivityExpirationEnabled?: boolean;
    ip?: string;
    loginExpirationEnabled?: boolean;
    loginExpired?: boolean;
    name?: string;
    os?: string;
    sshEnabled?: boolean;
    userId?: string;
}

/**
 * A collection of values returned by getPeers.
 */
export interface GetPeersResult {
    readonly approvalRequired: boolean;
    readonly cityName: string;
    readonly connected: boolean;
    readonly connectionIp: string;
    readonly countryCode: string;
    readonly dnsLabel: string;
    readonly extraDnsLabels: string[];
    readonly geonameId: number;
    readonly groups: string[];
    readonly hostname: string;
    readonly ids: string[];
    readonly inactivityExpirationEnabled: boolean;
    readonly ip: string;
    readonly kernelVersion: string;
    readonly lastLogin: string;
    readonly lastSeen: string;
    readonly loginExpirationEnabled: boolean;
    readonly loginExpired: boolean;
    readonly name: string;
    readonly os: string;
    readonly serialNumber: string;
    readonly sshEnabled: boolean;
    readonly uiVersion: string;
    readonly userId: string;
    readonly version: string;
}
export function getPeersOutput(args?: GetPeersOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPeersResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netbird:index/getPeers:getPeers", {
        "approvalRequired": args.approvalRequired,
        "cityName": args.cityName,
        "connected": args.connected,
        "connectionIp": args.connectionIp,
        "countryCode": args.countryCode,
        "dnsLabel": args.dnsLabel,
        "extraDnsLabels": args.extraDnsLabels,
        "geonameId": args.geonameId,
        "groups": args.groups,
        "hostname": args.hostname,
        "inactivityExpirationEnabled": args.inactivityExpirationEnabled,
        "ip": args.ip,
        "loginExpirationEnabled": args.loginExpirationEnabled,
        "loginExpired": args.loginExpired,
        "name": args.name,
        "os": args.os,
        "sshEnabled": args.sshEnabled,
        "userId": args.userId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPeers.
 */
export interface GetPeersOutputArgs {
    approvalRequired?: pulumi.Input<boolean | undefined>;
    cityName?: pulumi.Input<string | undefined>;
    connected?: pulumi.Input<boolean | undefined>;
    connectionIp?: pulumi.Input<string | undefined>;
    countryCode?: pulumi.Input<string | undefined>;
    dnsLabel?: pulumi.Input<string | undefined>;
    extraDnsLabels?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    geonameId?: pulumi.Input<number | undefined>;
    groups?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    hostname?: pulumi.Input<string | undefined>;
    inactivityExpirationEnabled?: pulumi.Input<boolean | undefined>;
    ip?: pulumi.Input<string | undefined>;
    loginExpirationEnabled?: pulumi.Input<boolean | undefined>;
    loginExpired?: pulumi.Input<boolean | undefined>;
    name?: pulumi.Input<string | undefined>;
    os?: pulumi.Input<string | undefined>;
    sshEnabled?: pulumi.Input<boolean | undefined>;
    userId?: pulumi.Input<string | undefined>;
}
