// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getPostureCheck(args?: GetPostureCheckArgs, opts?: pulumi.InvokeOptions): Promise<GetPostureCheckResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netbird:index/getPostureCheck:getPostureCheck", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPostureCheck.
 */
export interface GetPostureCheckArgs {
    id?: string;
    name?: string;
}

/**
 * A collection of values returned by getPostureCheck.
 */
export interface GetPostureCheckResult {
    readonly description: string;
    readonly geoLocationCheck: outputs.GetPostureCheckGeoLocationCheck;
    readonly id: string;
    readonly name: string;
    readonly netbirdVersionCheck: outputs.GetPostureCheckNetbirdVersionCheck;
    readonly osVersionCheck: outputs.GetPostureCheckOsVersionCheck;
    readonly peerNetworkRangeCheck: outputs.GetPostureCheckPeerNetworkRangeCheck;
    readonly processChecks: outputs.GetPostureCheckProcessCheck[];
}
export function getPostureCheckOutput(args?: GetPostureCheckOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPostureCheckResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netbird:index/getPostureCheck:getPostureCheck", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPostureCheck.
 */
export interface GetPostureCheckOutputArgs {
    id?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
}
