// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getPeer(args?: GetPeerArgs, opts?: pulumi.InvokeOptions): Promise<GetPeerResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netbird:index/getPeer:getPeer", {
        "id": args.id,
        "ip": args.ip,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPeer.
 */
export interface GetPeerArgs {
    id?: string;
    ip?: string;
    name?: string;
}

/**
 * A collection of values returned by getPeer.
 */
export interface GetPeerResult {
    readonly approvalRequired: boolean;
    readonly cityName: string;
    readonly connected: boolean;
    readonly connectionIp: string;
    readonly countryCode: string;
    readonly dnsLabel: string;
    readonly extraDnsLabels: string[];
    readonly geonameId: number;
    readonly groups: string[];
    readonly hostname: string;
    readonly id: string;
    readonly inactivityExpirationEnabled: boolean;
    readonly ip: string;
    readonly kernelVersion: string;
    readonly lastLogin: string;
    readonly lastSeen: string;
    readonly loginExpirationEnabled: boolean;
    readonly loginExpired: boolean;
    readonly name: string;
    readonly os: string;
    readonly serialNumber: string;
    readonly sshEnabled: boolean;
    readonly uiVersion: string;
    readonly userId: string;
    readonly version: string;
}
export function getPeerOutput(args?: GetPeerOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPeerResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netbird:index/getPeer:getPeer", {
        "id": args.id,
        "ip": args.ip,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPeer.
 */
export interface GetPeerOutputArgs {
    id?: pulumi.Input<string | undefined>;
    ip?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
}
