// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getReverseProxyClusters(opts?: pulumi.InvokeOptions): Promise<GetReverseProxyClustersResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netbird:index/getReverseProxyClusters:getReverseProxyClusters", {
    }, opts, utilities.getPackage());
}

/**
 * A collection of values returned by getReverseProxyClusters.
 */
export interface GetReverseProxyClustersResult {
    readonly clusters: outputs.GetReverseProxyClustersCluster[];
}
export function getReverseProxyClustersOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetReverseProxyClustersResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netbird:index/getReverseProxyClusters:getReverseProxyClusters", {
    }, opts, utilities.getPackage());
}
