// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getReverseProxyDomain(args?: GetReverseProxyDomainArgs, opts?: pulumi.InvokeOptions): Promise<GetReverseProxyDomainResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netbird:index/getReverseProxyDomain:getReverseProxyDomain", {
        "domain": args.domain,
        "id": args.id,
        "type": args.type,
        "validated": args.validated,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getReverseProxyDomain.
 */
export interface GetReverseProxyDomainArgs {
    domain?: string;
    id?: string;
    type?: string;
    validated?: boolean;
}

/**
 * A collection of values returned by getReverseProxyDomain.
 */
export interface GetReverseProxyDomainResult {
    readonly domain: string;
    readonly id: string;
    readonly targetCluster: string;
    readonly type: string;
    readonly validated: boolean;
}
export function getReverseProxyDomainOutput(args?: GetReverseProxyDomainOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetReverseProxyDomainResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netbird:index/getReverseProxyDomain:getReverseProxyDomain", {
        "domain": args.domain,
        "id": args.id,
        "type": args.type,
        "validated": args.validated,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getReverseProxyDomain.
 */
export interface GetReverseProxyDomainOutputArgs {
    domain?: pulumi.Input<string | undefined>;
    id?: pulumi.Input<string | undefined>;
    type?: pulumi.Input<string | undefined>;
    validated?: pulumi.Input<boolean | undefined>;
}
