// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getRoute(args?: GetRouteArgs, opts?: pulumi.InvokeOptions): Promise<GetRouteResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netbird:index/getRoute:getRoute", {
        "id": args.id,
        "networkId": args.networkId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRoute.
 */
export interface GetRouteArgs {
    id?: string;
    networkId?: string;
}

/**
 * A collection of values returned by getRoute.
 */
export interface GetRouteResult {
    readonly accessControlGroups: string[];
    readonly description: string;
    readonly domains: string[];
    readonly enabled: boolean;
    readonly groups: string[];
    readonly id: string;
    readonly keepRoute: boolean;
    readonly masquerade: boolean;
    readonly metric: number;
    readonly network: string;
    readonly networkId: string;
    readonly networkType: string;
    readonly peer: string;
    readonly peerGroups: string[];
    readonly skipAutoApply: boolean;
}
export function getRouteOutput(args?: GetRouteOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRouteResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netbird:index/getRoute:getRoute", {
        "id": args.id,
        "networkId": args.networkId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRoute.
 */
export interface GetRouteOutputArgs {
    id?: pulumi.Input<string | undefined>;
    networkId?: pulumi.Input<string | undefined>;
}
