// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getReverseProxyService(args?: GetReverseProxyServiceArgs, opts?: pulumi.InvokeOptions): Promise<GetReverseProxyServiceResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netbird:index/getReverseProxyService:getReverseProxyService", {
        "domain": args.domain,
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getReverseProxyService.
 */
export interface GetReverseProxyServiceArgs {
    domain?: string;
    id?: string;
    name?: string;
}

/**
 * A collection of values returned by getReverseProxyService.
 */
export interface GetReverseProxyServiceResult {
    readonly accessRestrictions: outputs.GetReverseProxyServiceAccessRestrictions;
    readonly auth: outputs.GetReverseProxyServiceAuth;
    readonly domain: string;
    readonly enabled: boolean;
    readonly id: string;
    readonly listenPort: number;
    readonly mode: string;
    readonly name: string;
    readonly passHostHeader: boolean;
    readonly portAutoAssigned: boolean;
    readonly proxyCluster: string;
    readonly rewriteRedirects: boolean;
    readonly targets: outputs.GetReverseProxyServiceTarget[];
}
export function getReverseProxyServiceOutput(args?: GetReverseProxyServiceOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetReverseProxyServiceResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netbird:index/getReverseProxyService:getReverseProxyService", {
        "domain": args.domain,
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getReverseProxyService.
 */
export interface GetReverseProxyServiceOutputArgs {
    domain?: pulumi.Input<string | undefined>;
    id?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
}
