// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSetupKey(args?: GetSetupKeyArgs, opts?: pulumi.InvokeOptions): Promise<GetSetupKeyResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netbird:index/getSetupKey:getSetupKey", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSetupKey.
 */
export interface GetSetupKeyArgs {
    id?: string;
    name?: string;
}

/**
 * A collection of values returned by getSetupKey.
 */
export interface GetSetupKeyResult {
    readonly allowExtraDnsLabels: boolean;
    readonly autoGroups: string[];
    readonly ephemeral: boolean;
    readonly expires: string;
    readonly id: string;
    readonly lastUsed: string;
    readonly name: string;
    readonly revoked: boolean;
    readonly state: string;
    readonly type: string;
    readonly updatedAt: string;
    readonly usageLimit: number;
    readonly usedTimes: number;
    readonly valid: boolean;
}
export function getSetupKeyOutput(args?: GetSetupKeyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSetupKeyResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netbird:index/getSetupKey:getSetupKey", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSetupKey.
 */
export interface GetSetupKeyOutputArgs {
    id?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
}
