// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getScim(args?: GetScimArgs, opts?: pulumi.InvokeOptions): Promise<GetScimResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netbird:index/getScim:getScim", {
        "id": args.id,
        "providerName": args.providerName,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getScim.
 */
export interface GetScimArgs {
    id?: string;
    providerName?: string;
}

/**
 * A collection of values returned by getScim.
 */
export interface GetScimResult {
    readonly enabled: boolean;
    readonly groupPrefixes: string[];
    readonly id: string;
    readonly lastSyncedAt: string;
    readonly providerName: string;
    readonly userGroupPrefixes: string[];
}
export function getScimOutput(args?: GetScimOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetScimResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netbird:index/getScim:getScim", {
        "id": args.id,
        "providerName": args.providerName,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getScim.
 */
export interface GetScimOutputArgs {
    id?: pulumi.Input<string | undefined>;
    providerName?: pulumi.Input<string | undefined>;
}
