// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getToken(args: GetTokenArgs, opts?: pulumi.InvokeOptions): Promise<GetTokenResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netbird:index/getToken:getToken", {
        "id": args.id,
        "name": args.name,
        "userId": args.userId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getToken.
 */
export interface GetTokenArgs {
    id?: string;
    name?: string;
    userId: string;
}

/**
 * A collection of values returned by getToken.
 */
export interface GetTokenResult {
    readonly createdAt: string;
    readonly expirationDate: string;
    readonly id: string;
    readonly lastUsed: string;
    readonly name: string;
    readonly userId: string;
}
export function getTokenOutput(args: GetTokenOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTokenResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netbird:index/getToken:getToken", {
        "id": args.id,
        "name": args.name,
        "userId": args.userId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getToken.
 */
export interface GetTokenOutputArgs {
    id?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
    userId: pulumi.Input<string>;
}
