// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Group extends pulumi.CustomResource {
    /**
     * Get an existing Group resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GroupState, opts?: pulumi.CustomResourceOptions): Group {
        return new Group(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netbird:index/group:Group';

    /**
     * Returns true if the given object is an instance of Group.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Group {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Group.__pulumiType;
    }

    /**
     * Group issued by
     */
    declare public /*out*/ readonly issued: pulumi.Output<string>;
    /**
     * Group name identifier
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * List of peers ids
     */
    declare public readonly peers: pulumi.Output<string[]>;
    /**
     * List of network resource ids
     */
    declare public readonly resources: pulumi.Output<string[]>;

    /**
     * Create a Group resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: GroupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GroupArgs | GroupState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GroupState | undefined;
            resourceInputs["issued"] = state?.issued;
            resourceInputs["name"] = state?.name;
            resourceInputs["peers"] = state?.peers;
            resourceInputs["resources"] = state?.resources;
        } else {
            const args = argsOrState as GroupArgs | undefined;
            resourceInputs["name"] = args?.name;
            resourceInputs["peers"] = args?.peers;
            resourceInputs["resources"] = args?.resources;
            resourceInputs["issued"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Group.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Group resources.
 */
export interface GroupState {
    /**
     * Group issued by
     */
    issued?: pulumi.Input<string | undefined>;
    /**
     * Group name identifier
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * List of peers ids
     */
    peers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * List of network resource ids
     */
    resources?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

/**
 * The set of arguments for constructing a Group resource.
 */
export interface GroupArgs {
    /**
     * Group name identifier
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * List of peers ids
     */
    peers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * List of network resource ids
     */
    resources?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}
