// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class IdentityProvider extends pulumi.CustomResource {
    /**
     * Get an existing IdentityProvider resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IdentityProviderState, opts?: pulumi.CustomResourceOptions): IdentityProvider {
        return new IdentityProvider(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netbird:index/identityProvider:IdentityProvider';

    /**
     * Returns true if the given object is an instance of IdentityProvider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IdentityProvider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IdentityProvider.__pulumiType;
    }

    /**
     * OAuth2 client ID
     */
    declare public readonly clientId: pulumi.Output<string>;
    /**
     * OAuth2 client secret
     */
    declare public readonly clientSecret: pulumi.Output<string>;
    /**
     * OIDC issuer URL
     */
    declare public readonly issuer: pulumi.Output<string>;
    /**
     * Human-readable name for the identity provider
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Type of identity provider (entra, google, microsoft, oidc, okta, pocketid, zitadel)
     */
    declare public readonly type: pulumi.Output<string>;

    /**
     * Create a IdentityProvider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IdentityProviderArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IdentityProviderArgs | IdentityProviderState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IdentityProviderState | undefined;
            resourceInputs["clientId"] = state?.clientId;
            resourceInputs["clientSecret"] = state?.clientSecret;
            resourceInputs["issuer"] = state?.issuer;
            resourceInputs["name"] = state?.name;
            resourceInputs["type"] = state?.type;
        } else {
            const args = argsOrState as IdentityProviderArgs | undefined;
            if (args?.clientId === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientId'");
            }
            if (args?.clientSecret === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientSecret'");
            }
            if (args?.issuer === undefined && !opts.urn) {
                throw new Error("Missing required property 'issuer'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["clientId"] = args?.clientId;
            resourceInputs["clientSecret"] = args?.clientSecret ? pulumi.secret(args.clientSecret) : undefined;
            resourceInputs["issuer"] = args?.issuer;
            resourceInputs["name"] = args?.name;
            resourceInputs["type"] = args?.type;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["clientSecret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(IdentityProvider.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering IdentityProvider resources.
 */
export interface IdentityProviderState {
    /**
     * OAuth2 client ID
     */
    clientId?: pulumi.Input<string | undefined>;
    /**
     * OAuth2 client secret
     */
    clientSecret?: pulumi.Input<string | undefined>;
    /**
     * OIDC issuer URL
     */
    issuer?: pulumi.Input<string | undefined>;
    /**
     * Human-readable name for the identity provider
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Type of identity provider (entra, google, microsoft, oidc, okta, pocketid, zitadel)
     */
    type?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IdentityProvider resource.
 */
export interface IdentityProviderArgs {
    /**
     * OAuth2 client ID
     */
    clientId: pulumi.Input<string>;
    /**
     * OAuth2 client secret
     */
    clientSecret: pulumi.Input<string>;
    /**
     * OIDC issuer URL
     */
    issuer: pulumi.Input<string>;
    /**
     * Human-readable name for the identity provider
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Type of identity provider (entra, google, microsoft, oidc, okta, pocketid, zitadel)
     */
    type: pulumi.Input<string>;
}
