// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { AccountSettingsArgs, AccountSettingsState } from "./accountSettings";
export type AccountSettings = import("./accountSettings").AccountSettings;
export const AccountSettings: typeof import("./accountSettings").AccountSettings = null as any;
utilities.lazyLoad(exports, ["AccountSettings"], () => require("./accountSettings"));

export { AgentNetworkGuardrailArgs, AgentNetworkGuardrailState } from "./agentNetworkGuardrail";
export type AgentNetworkGuardrail = import("./agentNetworkGuardrail").AgentNetworkGuardrail;
export const AgentNetworkGuardrail: typeof import("./agentNetworkGuardrail").AgentNetworkGuardrail = null as any;
utilities.lazyLoad(exports, ["AgentNetworkGuardrail"], () => require("./agentNetworkGuardrail"));

export { AgentNetworkPolicyArgs, AgentNetworkPolicyState } from "./agentNetworkPolicy";
export type AgentNetworkPolicy = import("./agentNetworkPolicy").AgentNetworkPolicy;
export const AgentNetworkPolicy: typeof import("./agentNetworkPolicy").AgentNetworkPolicy = null as any;
utilities.lazyLoad(exports, ["AgentNetworkPolicy"], () => require("./agentNetworkPolicy"));

export { AgentNetworkProviderArgs, AgentNetworkProviderState } from "./agentNetworkProvider";
export type AgentNetworkProvider = import("./agentNetworkProvider").AgentNetworkProvider;
export const AgentNetworkProvider: typeof import("./agentNetworkProvider").AgentNetworkProvider = null as any;
utilities.lazyLoad(exports, ["AgentNetworkProvider"], () => require("./agentNetworkProvider"));

export { AgentNetworkSettingsArgs, AgentNetworkSettingsState } from "./agentNetworkSettings";
export type AgentNetworkSettings = import("./agentNetworkSettings").AgentNetworkSettings;
export const AgentNetworkSettings: typeof import("./agentNetworkSettings").AgentNetworkSettings = null as any;
utilities.lazyLoad(exports, ["AgentNetworkSettings"], () => require("./agentNetworkSettings"));

export { DnsRecordArgs, DnsRecordState } from "./dnsRecord";
export type DnsRecord = import("./dnsRecord").DnsRecord;
export const DnsRecord: typeof import("./dnsRecord").DnsRecord = null as any;
utilities.lazyLoad(exports, ["DnsRecord"], () => require("./dnsRecord"));

export { DnsSettingsArgs, DnsSettingsState } from "./dnsSettings";
export type DnsSettings = import("./dnsSettings").DnsSettings;
export const DnsSettings: typeof import("./dnsSettings").DnsSettings = null as any;
utilities.lazyLoad(exports, ["DnsSettings"], () => require("./dnsSettings"));

export { DnsZoneArgs, DnsZoneState } from "./dnsZone";
export type DnsZone = import("./dnsZone").DnsZone;
export const DnsZone: typeof import("./dnsZone").DnsZone = null as any;
utilities.lazyLoad(exports, ["DnsZone"], () => require("./dnsZone"));

export { GetAccountSettingsResult } from "./getAccountSettings";
export const getAccountSettings: typeof import("./getAccountSettings").getAccountSettings = null as any;
export const getAccountSettingsOutput: typeof import("./getAccountSettings").getAccountSettingsOutput = null as any;
utilities.lazyLoad(exports, ["getAccountSettings","getAccountSettingsOutput"], () => require("./getAccountSettings"));

export { GetAgentNetworkGuardrailArgs, GetAgentNetworkGuardrailResult, GetAgentNetworkGuardrailOutputArgs } from "./getAgentNetworkGuardrail";
export const getAgentNetworkGuardrail: typeof import("./getAgentNetworkGuardrail").getAgentNetworkGuardrail = null as any;
export const getAgentNetworkGuardrailOutput: typeof import("./getAgentNetworkGuardrail").getAgentNetworkGuardrailOutput = null as any;
utilities.lazyLoad(exports, ["getAgentNetworkGuardrail","getAgentNetworkGuardrailOutput"], () => require("./getAgentNetworkGuardrail"));

export { GetAgentNetworkPolicyArgs, GetAgentNetworkPolicyResult, GetAgentNetworkPolicyOutputArgs } from "./getAgentNetworkPolicy";
export const getAgentNetworkPolicy: typeof import("./getAgentNetworkPolicy").getAgentNetworkPolicy = null as any;
export const getAgentNetworkPolicyOutput: typeof import("./getAgentNetworkPolicy").getAgentNetworkPolicyOutput = null as any;
utilities.lazyLoad(exports, ["getAgentNetworkPolicy","getAgentNetworkPolicyOutput"], () => require("./getAgentNetworkPolicy"));

export { GetAgentNetworkProviderArgs, GetAgentNetworkProviderResult, GetAgentNetworkProviderOutputArgs } from "./getAgentNetworkProvider";
export const getAgentNetworkProvider: typeof import("./getAgentNetworkProvider").getAgentNetworkProvider = null as any;
export const getAgentNetworkProviderOutput: typeof import("./getAgentNetworkProvider").getAgentNetworkProviderOutput = null as any;
utilities.lazyLoad(exports, ["getAgentNetworkProvider","getAgentNetworkProviderOutput"], () => require("./getAgentNetworkProvider"));

export { GetDnsRecordArgs, GetDnsRecordResult, GetDnsRecordOutputArgs } from "./getDnsRecord";
export const getDnsRecord: typeof import("./getDnsRecord").getDnsRecord = null as any;
export const getDnsRecordOutput: typeof import("./getDnsRecord").getDnsRecordOutput = null as any;
utilities.lazyLoad(exports, ["getDnsRecord","getDnsRecordOutput"], () => require("./getDnsRecord"));

export { GetDnsSettingsResult } from "./getDnsSettings";
export const getDnsSettings: typeof import("./getDnsSettings").getDnsSettings = null as any;
export const getDnsSettingsOutput: typeof import("./getDnsSettings").getDnsSettingsOutput = null as any;
utilities.lazyLoad(exports, ["getDnsSettings","getDnsSettingsOutput"], () => require("./getDnsSettings"));

export { GetDnsZoneArgs, GetDnsZoneResult, GetDnsZoneOutputArgs } from "./getDnsZone";
export const getDnsZone: typeof import("./getDnsZone").getDnsZone = null as any;
export const getDnsZoneOutput: typeof import("./getDnsZone").getDnsZoneOutput = null as any;
utilities.lazyLoad(exports, ["getDnsZone","getDnsZoneOutput"], () => require("./getDnsZone"));

export { GetGroupArgs, GetGroupResult, GetGroupOutputArgs } from "./getGroup";
export const getGroup: typeof import("./getGroup").getGroup = null as any;
export const getGroupOutput: typeof import("./getGroup").getGroupOutput = null as any;
utilities.lazyLoad(exports, ["getGroup","getGroupOutput"], () => require("./getGroup"));

export { GetIdentityProviderArgs, GetIdentityProviderResult, GetIdentityProviderOutputArgs } from "./getIdentityProvider";
export const getIdentityProvider: typeof import("./getIdentityProvider").getIdentityProvider = null as any;
export const getIdentityProviderOutput: typeof import("./getIdentityProvider").getIdentityProviderOutput = null as any;
utilities.lazyLoad(exports, ["getIdentityProvider","getIdentityProviderOutput"], () => require("./getIdentityProvider"));

export { GetNameserverGroupArgs, GetNameserverGroupResult, GetNameserverGroupOutputArgs } from "./getNameserverGroup";
export const getNameserverGroup: typeof import("./getNameserverGroup").getNameserverGroup = null as any;
export const getNameserverGroupOutput: typeof import("./getNameserverGroup").getNameserverGroupOutput = null as any;
utilities.lazyLoad(exports, ["getNameserverGroup","getNameserverGroupOutput"], () => require("./getNameserverGroup"));

export { GetNetworkArgs, GetNetworkResult, GetNetworkOutputArgs } from "./getNetwork";
export const getNetwork: typeof import("./getNetwork").getNetwork = null as any;
export const getNetworkOutput: typeof import("./getNetwork").getNetworkOutput = null as any;
utilities.lazyLoad(exports, ["getNetwork","getNetworkOutput"], () => require("./getNetwork"));

export { GetNetworkResourceArgs, GetNetworkResourceResult, GetNetworkResourceOutputArgs } from "./getNetworkResource";
export const getNetworkResource: typeof import("./getNetworkResource").getNetworkResource = null as any;
export const getNetworkResourceOutput: typeof import("./getNetworkResource").getNetworkResourceOutput = null as any;
utilities.lazyLoad(exports, ["getNetworkResource","getNetworkResourceOutput"], () => require("./getNetworkResource"));

export { GetNetworkRouterArgs, GetNetworkRouterResult, GetNetworkRouterOutputArgs } from "./getNetworkRouter";
export const getNetworkRouter: typeof import("./getNetworkRouter").getNetworkRouter = null as any;
export const getNetworkRouterOutput: typeof import("./getNetworkRouter").getNetworkRouterOutput = null as any;
utilities.lazyLoad(exports, ["getNetworkRouter","getNetworkRouterOutput"], () => require("./getNetworkRouter"));

export { GetPeerArgs, GetPeerResult, GetPeerOutputArgs } from "./getPeer";
export const getPeer: typeof import("./getPeer").getPeer = null as any;
export const getPeerOutput: typeof import("./getPeer").getPeerOutput = null as any;
utilities.lazyLoad(exports, ["getPeer","getPeerOutput"], () => require("./getPeer"));

export { GetPeersArgs, GetPeersResult, GetPeersOutputArgs } from "./getPeers";
export const getPeers: typeof import("./getPeers").getPeers = null as any;
export const getPeersOutput: typeof import("./getPeers").getPeersOutput = null as any;
utilities.lazyLoad(exports, ["getPeers","getPeersOutput"], () => require("./getPeers"));

export { GetPolicyArgs, GetPolicyResult, GetPolicyOutputArgs } from "./getPolicy";
export const getPolicy: typeof import("./getPolicy").getPolicy = null as any;
export const getPolicyOutput: typeof import("./getPolicy").getPolicyOutput = null as any;
utilities.lazyLoad(exports, ["getPolicy","getPolicyOutput"], () => require("./getPolicy"));

export { GetPostureCheckArgs, GetPostureCheckResult, GetPostureCheckOutputArgs } from "./getPostureCheck";
export const getPostureCheck: typeof import("./getPostureCheck").getPostureCheck = null as any;
export const getPostureCheckOutput: typeof import("./getPostureCheck").getPostureCheckOutput = null as any;
utilities.lazyLoad(exports, ["getPostureCheck","getPostureCheckOutput"], () => require("./getPostureCheck"));

export { GetReverseProxyClustersResult } from "./getReverseProxyClusters";
export const getReverseProxyClusters: typeof import("./getReverseProxyClusters").getReverseProxyClusters = null as any;
export const getReverseProxyClustersOutput: typeof import("./getReverseProxyClusters").getReverseProxyClustersOutput = null as any;
utilities.lazyLoad(exports, ["getReverseProxyClusters","getReverseProxyClustersOutput"], () => require("./getReverseProxyClusters"));

export { GetReverseProxyDomainArgs, GetReverseProxyDomainResult, GetReverseProxyDomainOutputArgs } from "./getReverseProxyDomain";
export const getReverseProxyDomain: typeof import("./getReverseProxyDomain").getReverseProxyDomain = null as any;
export const getReverseProxyDomainOutput: typeof import("./getReverseProxyDomain").getReverseProxyDomainOutput = null as any;
utilities.lazyLoad(exports, ["getReverseProxyDomain","getReverseProxyDomainOutput"], () => require("./getReverseProxyDomain"));

export { GetReverseProxyServiceArgs, GetReverseProxyServiceResult, GetReverseProxyServiceOutputArgs } from "./getReverseProxyService";
export const getReverseProxyService: typeof import("./getReverseProxyService").getReverseProxyService = null as any;
export const getReverseProxyServiceOutput: typeof import("./getReverseProxyService").getReverseProxyServiceOutput = null as any;
utilities.lazyLoad(exports, ["getReverseProxyService","getReverseProxyServiceOutput"], () => require("./getReverseProxyService"));

export { GetRouteArgs, GetRouteResult, GetRouteOutputArgs } from "./getRoute";
export const getRoute: typeof import("./getRoute").getRoute = null as any;
export const getRouteOutput: typeof import("./getRoute").getRouteOutput = null as any;
utilities.lazyLoad(exports, ["getRoute","getRouteOutput"], () => require("./getRoute"));

export { GetScimArgs, GetScimResult, GetScimOutputArgs } from "./getScim";
export const getScim: typeof import("./getScim").getScim = null as any;
export const getScimOutput: typeof import("./getScim").getScimOutput = null as any;
utilities.lazyLoad(exports, ["getScim","getScimOutput"], () => require("./getScim"));

export { GetSetupKeyArgs, GetSetupKeyResult, GetSetupKeyOutputArgs } from "./getSetupKey";
export const getSetupKey: typeof import("./getSetupKey").getSetupKey = null as any;
export const getSetupKeyOutput: typeof import("./getSetupKey").getSetupKeyOutput = null as any;
utilities.lazyLoad(exports, ["getSetupKey","getSetupKeyOutput"], () => require("./getSetupKey"));

export { GetTokenArgs, GetTokenResult, GetTokenOutputArgs } from "./getToken";
export const getToken: typeof import("./getToken").getToken = null as any;
export const getTokenOutput: typeof import("./getToken").getTokenOutput = null as any;
utilities.lazyLoad(exports, ["getToken","getTokenOutput"], () => require("./getToken"));

export { GetUserArgs, GetUserResult, GetUserOutputArgs } from "./getUser";
export const getUser: typeof import("./getUser").getUser = null as any;
export const getUserOutput: typeof import("./getUser").getUserOutput = null as any;
utilities.lazyLoad(exports, ["getUser","getUserOutput"], () => require("./getUser"));

export { GroupArgs, GroupState } from "./group";
export type Group = import("./group").Group;
export const Group: typeof import("./group").Group = null as any;
utilities.lazyLoad(exports, ["Group"], () => require("./group"));

export { IdentityProviderArgs, IdentityProviderState } from "./identityProvider";
export type IdentityProvider = import("./identityProvider").IdentityProvider;
export const IdentityProvider: typeof import("./identityProvider").IdentityProvider = null as any;
utilities.lazyLoad(exports, ["IdentityProvider"], () => require("./identityProvider"));

export { NameserverGroupArgs, NameserverGroupState } from "./nameserverGroup";
export type NameserverGroup = import("./nameserverGroup").NameserverGroup;
export const NameserverGroup: typeof import("./nameserverGroup").NameserverGroup = null as any;
utilities.lazyLoad(exports, ["NameserverGroup"], () => require("./nameserverGroup"));

export { NetworkArgs, NetworkState } from "./network";
export type Network = import("./network").Network;
export const Network: typeof import("./network").Network = null as any;
utilities.lazyLoad(exports, ["Network"], () => require("./network"));

export { NetworkResourceArgs, NetworkResourceState } from "./networkResource";
export type NetworkResource = import("./networkResource").NetworkResource;
export const NetworkResource: typeof import("./networkResource").NetworkResource = null as any;
utilities.lazyLoad(exports, ["NetworkResource"], () => require("./networkResource"));

export { NetworkRouterArgs, NetworkRouterState } from "./networkRouter";
export type NetworkRouter = import("./networkRouter").NetworkRouter;
export const NetworkRouter: typeof import("./networkRouter").NetworkRouter = null as any;
utilities.lazyLoad(exports, ["NetworkRouter"], () => require("./networkRouter"));

export { PeerArgs, PeerState } from "./peer";
export type Peer = import("./peer").Peer;
export const Peer: typeof import("./peer").Peer = null as any;
utilities.lazyLoad(exports, ["Peer"], () => require("./peer"));

export { PolicyArgs, PolicyState } from "./policy";
export type Policy = import("./policy").Policy;
export const Policy: typeof import("./policy").Policy = null as any;
utilities.lazyLoad(exports, ["Policy"], () => require("./policy"));

export { PostureCheckArgs, PostureCheckState } from "./postureCheck";
export type PostureCheck = import("./postureCheck").PostureCheck;
export const PostureCheck: typeof import("./postureCheck").PostureCheck = null as any;
utilities.lazyLoad(exports, ["PostureCheck"], () => require("./postureCheck"));

export * from "./provider";
import { Provider } from "./provider";

export { ReverseProxyDomainArgs, ReverseProxyDomainState } from "./reverseProxyDomain";
export type ReverseProxyDomain = import("./reverseProxyDomain").ReverseProxyDomain;
export const ReverseProxyDomain: typeof import("./reverseProxyDomain").ReverseProxyDomain = null as any;
utilities.lazyLoad(exports, ["ReverseProxyDomain"], () => require("./reverseProxyDomain"));

export { ReverseProxyServiceArgs, ReverseProxyServiceState } from "./reverseProxyService";
export type ReverseProxyService = import("./reverseProxyService").ReverseProxyService;
export const ReverseProxyService: typeof import("./reverseProxyService").ReverseProxyService = null as any;
utilities.lazyLoad(exports, ["ReverseProxyService"], () => require("./reverseProxyService"));

export { RouteArgs, RouteState } from "./route";
export type Route = import("./route").Route;
export const Route: typeof import("./route").Route = null as any;
utilities.lazyLoad(exports, ["Route"], () => require("./route"));

export { ScimArgs, ScimState } from "./scim";
export type Scim = import("./scim").Scim;
export const Scim: typeof import("./scim").Scim = null as any;
utilities.lazyLoad(exports, ["Scim"], () => require("./scim"));

export { SetupKeyArgs, SetupKeyState } from "./setupKey";
export type SetupKey = import("./setupKey").SetupKey;
export const SetupKey: typeof import("./setupKey").SetupKey = null as any;
utilities.lazyLoad(exports, ["SetupKey"], () => require("./setupKey"));

export { TokenArgs, TokenState } from "./token";
export type Token = import("./token").Token;
export const Token: typeof import("./token").Token = null as any;
utilities.lazyLoad(exports, ["Token"], () => require("./token"));

export { UserArgs, UserState } from "./user";
export type User = import("./user").User;
export const User: typeof import("./user").User = null as any;
utilities.lazyLoad(exports, ["User"], () => require("./user"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "netbird:index/accountSettings:AccountSettings":
                return new AccountSettings(name, <any>undefined, { urn })
            case "netbird:index/agentNetworkGuardrail:AgentNetworkGuardrail":
                return new AgentNetworkGuardrail(name, <any>undefined, { urn })
            case "netbird:index/agentNetworkPolicy:AgentNetworkPolicy":
                return new AgentNetworkPolicy(name, <any>undefined, { urn })
            case "netbird:index/agentNetworkProvider:AgentNetworkProvider":
                return new AgentNetworkProvider(name, <any>undefined, { urn })
            case "netbird:index/agentNetworkSettings:AgentNetworkSettings":
                return new AgentNetworkSettings(name, <any>undefined, { urn })
            case "netbird:index/dnsRecord:DnsRecord":
                return new DnsRecord(name, <any>undefined, { urn })
            case "netbird:index/dnsSettings:DnsSettings":
                return new DnsSettings(name, <any>undefined, { urn })
            case "netbird:index/dnsZone:DnsZone":
                return new DnsZone(name, <any>undefined, { urn })
            case "netbird:index/group:Group":
                return new Group(name, <any>undefined, { urn })
            case "netbird:index/identityProvider:IdentityProvider":
                return new IdentityProvider(name, <any>undefined, { urn })
            case "netbird:index/nameserverGroup:NameserverGroup":
                return new NameserverGroup(name, <any>undefined, { urn })
            case "netbird:index/network:Network":
                return new Network(name, <any>undefined, { urn })
            case "netbird:index/networkResource:NetworkResource":
                return new NetworkResource(name, <any>undefined, { urn })
            case "netbird:index/networkRouter:NetworkRouter":
                return new NetworkRouter(name, <any>undefined, { urn })
            case "netbird:index/peer:Peer":
                return new Peer(name, <any>undefined, { urn })
            case "netbird:index/policy:Policy":
                return new Policy(name, <any>undefined, { urn })
            case "netbird:index/postureCheck:PostureCheck":
                return new PostureCheck(name, <any>undefined, { urn })
            case "netbird:index/reverseProxyDomain:ReverseProxyDomain":
                return new ReverseProxyDomain(name, <any>undefined, { urn })
            case "netbird:index/reverseProxyService:ReverseProxyService":
                return new ReverseProxyService(name, <any>undefined, { urn })
            case "netbird:index/route:Route":
                return new Route(name, <any>undefined, { urn })
            case "netbird:index/scim:Scim":
                return new Scim(name, <any>undefined, { urn })
            case "netbird:index/setupKey:SetupKey":
                return new SetupKey(name, <any>undefined, { urn })
            case "netbird:index/token:Token":
                return new Token(name, <any>undefined, { urn })
            case "netbird:index/user:User":
                return new User(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("netbird", "index/accountSettings", _module)
pulumi.runtime.registerResourceModule("netbird", "index/agentNetworkGuardrail", _module)
pulumi.runtime.registerResourceModule("netbird", "index/agentNetworkPolicy", _module)
pulumi.runtime.registerResourceModule("netbird", "index/agentNetworkProvider", _module)
pulumi.runtime.registerResourceModule("netbird", "index/agentNetworkSettings", _module)
pulumi.runtime.registerResourceModule("netbird", "index/dnsRecord", _module)
pulumi.runtime.registerResourceModule("netbird", "index/dnsSettings", _module)
pulumi.runtime.registerResourceModule("netbird", "index/dnsZone", _module)
pulumi.runtime.registerResourceModule("netbird", "index/group", _module)
pulumi.runtime.registerResourceModule("netbird", "index/identityProvider", _module)
pulumi.runtime.registerResourceModule("netbird", "index/nameserverGroup", _module)
pulumi.runtime.registerResourceModule("netbird", "index/network", _module)
pulumi.runtime.registerResourceModule("netbird", "index/networkResource", _module)
pulumi.runtime.registerResourceModule("netbird", "index/networkRouter", _module)
pulumi.runtime.registerResourceModule("netbird", "index/peer", _module)
pulumi.runtime.registerResourceModule("netbird", "index/policy", _module)
pulumi.runtime.registerResourceModule("netbird", "index/postureCheck", _module)
pulumi.runtime.registerResourceModule("netbird", "index/reverseProxyDomain", _module)
pulumi.runtime.registerResourceModule("netbird", "index/reverseProxyService", _module)
pulumi.runtime.registerResourceModule("netbird", "index/route", _module)
pulumi.runtime.registerResourceModule("netbird", "index/scim", _module)
pulumi.runtime.registerResourceModule("netbird", "index/setupKey", _module)
pulumi.runtime.registerResourceModule("netbird", "index/token", _module)
pulumi.runtime.registerResourceModule("netbird", "index/user", _module)
pulumi.runtime.registerResourcePackage("netbird", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:netbird") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
