// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class NameserverGroup extends pulumi.CustomResource {
    /**
     * Get an existing NameserverGroup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NameserverGroupState, opts?: pulumi.CustomResourceOptions): NameserverGroup {
        return new NameserverGroup(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netbird:index/nameserverGroup:NameserverGroup';

    /**
     * Returns true if the given object is an instance of NameserverGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NameserverGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NameserverGroup.__pulumiType;
    }

    /**
     * Description of the nameserver group
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Match domain list. It should be empty only if primary is true.
     */
    declare public readonly domains: pulumi.Output<string[]>;
    /**
     * Nameserver group status
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * Distribution group IDs that defines group of peers that will use this nameserver group
     */
    declare public readonly groups: pulumi.Output<string[]>;
    /**
     * Name of nameserver group
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Nameserver list
     */
    declare public readonly nameservers: pulumi.Output<outputs.NameserverGroupNameserver[]>;
    /**
     * Defines if a nameserver group is primary that resolves all domains. It should be true only if domains list is empty.
     */
    declare public readonly primary: pulumi.Output<boolean>;
    /**
     * Search domain status for match domains. It should be true only if domains list is not empty.
     */
    declare public readonly searchDomainsEnabled: pulumi.Output<boolean>;

    /**
     * Create a NameserverGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NameserverGroupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NameserverGroupArgs | NameserverGroupState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NameserverGroupState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["domains"] = state?.domains;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["groups"] = state?.groups;
            resourceInputs["name"] = state?.name;
            resourceInputs["nameservers"] = state?.nameservers;
            resourceInputs["primary"] = state?.primary;
            resourceInputs["searchDomainsEnabled"] = state?.searchDomainsEnabled;
        } else {
            const args = argsOrState as NameserverGroupArgs | undefined;
            if (args?.groups === undefined && !opts.urn) {
                throw new Error("Missing required property 'groups'");
            }
            if (args?.nameservers === undefined && !opts.urn) {
                throw new Error("Missing required property 'nameservers'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["domains"] = args?.domains;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["groups"] = args?.groups;
            resourceInputs["name"] = args?.name;
            resourceInputs["nameservers"] = args?.nameservers;
            resourceInputs["primary"] = args?.primary;
            resourceInputs["searchDomainsEnabled"] = args?.searchDomainsEnabled;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NameserverGroup.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering NameserverGroup resources.
 */
export interface NameserverGroupState {
    /**
     * Description of the nameserver group
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Match domain list. It should be empty only if primary is true.
     */
    domains?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Nameserver group status
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Distribution group IDs that defines group of peers that will use this nameserver group
     */
    groups?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Name of nameserver group
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Nameserver list
     */
    nameservers?: pulumi.Input<pulumi.Input<inputs.NameserverGroupNameserver>[] | undefined>;
    /**
     * Defines if a nameserver group is primary that resolves all domains. It should be true only if domains list is empty.
     */
    primary?: pulumi.Input<boolean | undefined>;
    /**
     * Search domain status for match domains. It should be true only if domains list is not empty.
     */
    searchDomainsEnabled?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a NameserverGroup resource.
 */
export interface NameserverGroupArgs {
    /**
     * Description of the nameserver group
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Match domain list. It should be empty only if primary is true.
     */
    domains?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Nameserver group status
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Distribution group IDs that defines group of peers that will use this nameserver group
     */
    groups: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Name of nameserver group
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Nameserver list
     */
    nameservers: pulumi.Input<pulumi.Input<inputs.NameserverGroupNameserver>[]>;
    /**
     * Defines if a nameserver group is primary that resolves all domains. It should be true only if domains list is empty.
     */
    primary?: pulumi.Input<boolean | undefined>;
    /**
     * Search domain status for match domains. It should be true only if domains list is not empty.
     */
    searchDomainsEnabled?: pulumi.Input<boolean | undefined>;
}
