// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Network extends pulumi.CustomResource {
    /**
     * Get an existing Network resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NetworkState, opts?: pulumi.CustomResourceOptions): Network {
        return new Network(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netbird:index/network:Network';

    /**
     * Returns true if the given object is an instance of Network.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Network {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Network.__pulumiType;
    }

    /**
     * Network Description
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Network Name
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Policy IDs associated with resources inside this Network
     */
    declare public /*out*/ readonly policies: pulumi.Output<string[]>;
    /**
     * Network Resource IDs
     */
    declare public /*out*/ readonly resources: pulumi.Output<string[]>;
    /**
     * Network Router IDs
     */
    declare public /*out*/ readonly routers: pulumi.Output<string[]>;

    /**
     * Create a Network resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: NetworkArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NetworkArgs | NetworkState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NetworkState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["name"] = state?.name;
            resourceInputs["policies"] = state?.policies;
            resourceInputs["resources"] = state?.resources;
            resourceInputs["routers"] = state?.routers;
        } else {
            const args = argsOrState as NetworkArgs | undefined;
            resourceInputs["description"] = args?.description;
            resourceInputs["name"] = args?.name;
            resourceInputs["policies"] = undefined /*out*/;
            resourceInputs["resources"] = undefined /*out*/;
            resourceInputs["routers"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Network.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Network resources.
 */
export interface NetworkState {
    /**
     * Network Description
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Network Name
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Policy IDs associated with resources inside this Network
     */
    policies?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Network Resource IDs
     */
    resources?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Network Router IDs
     */
    routers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

/**
 * The set of arguments for constructing a Network resource.
 */
export interface NetworkArgs {
    /**
     * Network Description
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Network Name
     */
    name?: pulumi.Input<string | undefined>;
}
