// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class NetworkResource extends pulumi.CustomResource {
    /**
     * Get an existing NetworkResource resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NetworkResourceState, opts?: pulumi.CustomResourceOptions): NetworkResource {
        return new NetworkResource(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netbird:index/networkResource:NetworkResource';

    /**
     * Returns true if the given object is an instance of NetworkResource.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NetworkResource {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NetworkResource.__pulumiType;
    }

    /**
     * Network resource address (either a direct host like 1.1.1.1 or 1.1.1.1/32, or a subnet like 192.168.178.0/24, or domains like example.com and *.example.com)
     */
    declare public readonly address: pulumi.Output<string>;
    /**
     * NetworkResource Description
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * NetworkResource status
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * Group IDs containing the resource
     */
    declare public readonly groups: pulumi.Output<string[]>;
    /**
     * NetworkResource Name
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The unique identifier of a network
     */
    declare public readonly networkId: pulumi.Output<string>;

    /**
     * Create a NetworkResource resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NetworkResourceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NetworkResourceArgs | NetworkResourceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NetworkResourceState | undefined;
            resourceInputs["address"] = state?.address;
            resourceInputs["description"] = state?.description;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["groups"] = state?.groups;
            resourceInputs["name"] = state?.name;
            resourceInputs["networkId"] = state?.networkId;
        } else {
            const args = argsOrState as NetworkResourceArgs | undefined;
            if (args?.address === undefined && !opts.urn) {
                throw new Error("Missing required property 'address'");
            }
            if (args?.groups === undefined && !opts.urn) {
                throw new Error("Missing required property 'groups'");
            }
            if (args?.networkId === undefined && !opts.urn) {
                throw new Error("Missing required property 'networkId'");
            }
            resourceInputs["address"] = args?.address;
            resourceInputs["description"] = args?.description;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["groups"] = args?.groups;
            resourceInputs["name"] = args?.name;
            resourceInputs["networkId"] = args?.networkId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NetworkResource.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering NetworkResource resources.
 */
export interface NetworkResourceState {
    /**
     * Network resource address (either a direct host like 1.1.1.1 or 1.1.1.1/32, or a subnet like 192.168.178.0/24, or domains like example.com and *.example.com)
     */
    address?: pulumi.Input<string | undefined>;
    /**
     * NetworkResource Description
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * NetworkResource status
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Group IDs containing the resource
     */
    groups?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * NetworkResource Name
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The unique identifier of a network
     */
    networkId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a NetworkResource resource.
 */
export interface NetworkResourceArgs {
    /**
     * Network resource address (either a direct host like 1.1.1.1 or 1.1.1.1/32, or a subnet like 192.168.178.0/24, or domains like example.com and *.example.com)
     */
    address: pulumi.Input<string>;
    /**
     * NetworkResource Description
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * NetworkResource status
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Group IDs containing the resource
     */
    groups: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * NetworkResource Name
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The unique identifier of a network
     */
    networkId: pulumi.Input<string>;
}
