// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Peer extends pulumi.CustomResource {
    /**
     * Get an existing Peer resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PeerState, opts?: pulumi.CustomResourceOptions): Peer {
        return new Peer(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netbird:index/peer:Peer';

    /**
     * Returns true if the given object is an instance of Peer.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Peer {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Peer.__pulumiType;
    }

    /**
     * Indicates whether peer needs approval
     */
    declare public readonly approvalRequired: pulumi.Output<boolean>;
    /**
     * Peer city name
     */
    declare public /*out*/ readonly cityName: pulumi.Output<string>;
    /**
     * Peer Connection Status
     */
    declare public /*out*/ readonly connected: pulumi.Output<boolean>;
    /**
     * Peer Public IP
     */
    declare public /*out*/ readonly connectionIp: pulumi.Output<string>;
    /**
     * Peer country code
     */
    declare public /*out*/ readonly countryCode: pulumi.Output<string>;
    /**
     * Peer DNS Label
     */
    declare public /*out*/ readonly dnsLabel: pulumi.Output<string>;
    /**
     * Peer extra DNS Labels
     */
    declare public /*out*/ readonly extraDnsLabels: pulumi.Output<string[]>;
    /**
     * Peer Location ID
     */
    declare public /*out*/ readonly geonameId: pulumi.Output<number>;
    /**
     * Peer groups
     */
    declare public /*out*/ readonly groups: pulumi.Output<string[]>;
    /**
     * Peer's HOSTNAME
     */
    declare public /*out*/ readonly hostname: pulumi.Output<string>;
    /**
     * Enable inactivity expiration for peer
     */
    declare public readonly inactivityExpirationEnabled: pulumi.Output<boolean>;
    /**
     * Peer  IP
     */
    declare public /*out*/ readonly ip: pulumi.Output<string>;
    /**
     * Peer Kernel Version
     */
    declare public /*out*/ readonly kernelVersion: pulumi.Output<string>;
    /**
     * Time of peer last login
     */
    declare public /*out*/ readonly lastLogin: pulumi.Output<string>;
    /**
     * Peer Last Seen timedate
     */
    declare public /*out*/ readonly lastSeen: pulumi.Output<string>;
    /**
     * Indicates whether login expiration is enabled for peer
     */
    declare public readonly loginExpirationEnabled: pulumi.Output<boolean>;
    /**
     * Indicates whether peer login is expired
     */
    declare public /*out*/ readonly loginExpired: pulumi.Output<boolean>;
    /**
     * Peer Name
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Peer OS
     */
    declare public /*out*/ readonly os: pulumi.Output<string>;
    /**
     * Peer ID
     */
    declare public readonly peerId: pulumi.Output<string>;
    /**
     * Peer device serial number
     */
    declare public /*out*/ readonly serialNumber: pulumi.Output<string>;
    /**
     * Enable SSH to Peer
     */
    declare public readonly sshEnabled: pulumi.Output<boolean>;
    /**
     * Peer  UI Version
     */
    declare public /*out*/ readonly uiVersion: pulumi.Output<string>;
    /**
     * User ID of peer
     */
    declare public /*out*/ readonly userId: pulumi.Output<string>;
    /**
     * Peer  Version
     */
    declare public /*out*/ readonly version: pulumi.Output<string>;

    /**
     * Create a Peer resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PeerArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PeerArgs | PeerState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PeerState | undefined;
            resourceInputs["approvalRequired"] = state?.approvalRequired;
            resourceInputs["cityName"] = state?.cityName;
            resourceInputs["connected"] = state?.connected;
            resourceInputs["connectionIp"] = state?.connectionIp;
            resourceInputs["countryCode"] = state?.countryCode;
            resourceInputs["dnsLabel"] = state?.dnsLabel;
            resourceInputs["extraDnsLabels"] = state?.extraDnsLabels;
            resourceInputs["geonameId"] = state?.geonameId;
            resourceInputs["groups"] = state?.groups;
            resourceInputs["hostname"] = state?.hostname;
            resourceInputs["inactivityExpirationEnabled"] = state?.inactivityExpirationEnabled;
            resourceInputs["ip"] = state?.ip;
            resourceInputs["kernelVersion"] = state?.kernelVersion;
            resourceInputs["lastLogin"] = state?.lastLogin;
            resourceInputs["lastSeen"] = state?.lastSeen;
            resourceInputs["loginExpirationEnabled"] = state?.loginExpirationEnabled;
            resourceInputs["loginExpired"] = state?.loginExpired;
            resourceInputs["name"] = state?.name;
            resourceInputs["os"] = state?.os;
            resourceInputs["peerId"] = state?.peerId;
            resourceInputs["serialNumber"] = state?.serialNumber;
            resourceInputs["sshEnabled"] = state?.sshEnabled;
            resourceInputs["uiVersion"] = state?.uiVersion;
            resourceInputs["userId"] = state?.userId;
            resourceInputs["version"] = state?.version;
        } else {
            const args = argsOrState as PeerArgs | undefined;
            if (args?.peerId === undefined && !opts.urn) {
                throw new Error("Missing required property 'peerId'");
            }
            resourceInputs["approvalRequired"] = args?.approvalRequired;
            resourceInputs["inactivityExpirationEnabled"] = args?.inactivityExpirationEnabled;
            resourceInputs["loginExpirationEnabled"] = args?.loginExpirationEnabled;
            resourceInputs["name"] = args?.name;
            resourceInputs["peerId"] = args?.peerId;
            resourceInputs["sshEnabled"] = args?.sshEnabled;
            resourceInputs["cityName"] = undefined /*out*/;
            resourceInputs["connected"] = undefined /*out*/;
            resourceInputs["connectionIp"] = undefined /*out*/;
            resourceInputs["countryCode"] = undefined /*out*/;
            resourceInputs["dnsLabel"] = undefined /*out*/;
            resourceInputs["extraDnsLabels"] = undefined /*out*/;
            resourceInputs["geonameId"] = undefined /*out*/;
            resourceInputs["groups"] = undefined /*out*/;
            resourceInputs["hostname"] = undefined /*out*/;
            resourceInputs["ip"] = undefined /*out*/;
            resourceInputs["kernelVersion"] = undefined /*out*/;
            resourceInputs["lastLogin"] = undefined /*out*/;
            resourceInputs["lastSeen"] = undefined /*out*/;
            resourceInputs["loginExpired"] = undefined /*out*/;
            resourceInputs["os"] = undefined /*out*/;
            resourceInputs["serialNumber"] = undefined /*out*/;
            resourceInputs["uiVersion"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
            resourceInputs["version"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Peer.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Peer resources.
 */
export interface PeerState {
    /**
     * Indicates whether peer needs approval
     */
    approvalRequired?: pulumi.Input<boolean | undefined>;
    /**
     * Peer city name
     */
    cityName?: pulumi.Input<string | undefined>;
    /**
     * Peer Connection Status
     */
    connected?: pulumi.Input<boolean | undefined>;
    /**
     * Peer Public IP
     */
    connectionIp?: pulumi.Input<string | undefined>;
    /**
     * Peer country code
     */
    countryCode?: pulumi.Input<string | undefined>;
    /**
     * Peer DNS Label
     */
    dnsLabel?: pulumi.Input<string | undefined>;
    /**
     * Peer extra DNS Labels
     */
    extraDnsLabels?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Peer Location ID
     */
    geonameId?: pulumi.Input<number | undefined>;
    /**
     * Peer groups
     */
    groups?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Peer's HOSTNAME
     */
    hostname?: pulumi.Input<string | undefined>;
    /**
     * Enable inactivity expiration for peer
     */
    inactivityExpirationEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * Peer  IP
     */
    ip?: pulumi.Input<string | undefined>;
    /**
     * Peer Kernel Version
     */
    kernelVersion?: pulumi.Input<string | undefined>;
    /**
     * Time of peer last login
     */
    lastLogin?: pulumi.Input<string | undefined>;
    /**
     * Peer Last Seen timedate
     */
    lastSeen?: pulumi.Input<string | undefined>;
    /**
     * Indicates whether login expiration is enabled for peer
     */
    loginExpirationEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * Indicates whether peer login is expired
     */
    loginExpired?: pulumi.Input<boolean | undefined>;
    /**
     * Peer Name
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Peer OS
     */
    os?: pulumi.Input<string | undefined>;
    /**
     * Peer ID
     */
    peerId?: pulumi.Input<string | undefined>;
    /**
     * Peer device serial number
     */
    serialNumber?: pulumi.Input<string | undefined>;
    /**
     * Enable SSH to Peer
     */
    sshEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * Peer  UI Version
     */
    uiVersion?: pulumi.Input<string | undefined>;
    /**
     * User ID of peer
     */
    userId?: pulumi.Input<string | undefined>;
    /**
     * Peer  Version
     */
    version?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Peer resource.
 */
export interface PeerArgs {
    /**
     * Indicates whether peer needs approval
     */
    approvalRequired?: pulumi.Input<boolean | undefined>;
    /**
     * Enable inactivity expiration for peer
     */
    inactivityExpirationEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * Indicates whether login expiration is enabled for peer
     */
    loginExpirationEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * Peer Name
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Peer ID
     */
    peerId: pulumi.Input<string>;
    /**
     * Enable SSH to Peer
     */
    sshEnabled?: pulumi.Input<boolean | undefined>;
}
