// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Policy extends pulumi.CustomResource {
    /**
     * Get an existing Policy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PolicyState, opts?: pulumi.CustomResourceOptions): Policy {
        return new Policy(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netbird:index/policy:Policy';

    /**
     * Returns true if the given object is an instance of Policy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Policy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Policy.__pulumiType;
    }

    /**
     * Policy Description
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Policy enabled
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * Policy Name
     */
    declare public readonly name: pulumi.Output<string>;
    declare public readonly rules: pulumi.Output<outputs.PolicyRule[] | undefined>;
    /**
     * Posture checks associated with policy
     */
    declare public readonly sourcePostureChecks: pulumi.Output<string[]>;

    /**
     * Create a Policy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PolicyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PolicyArgs | PolicyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PolicyState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["name"] = state?.name;
            resourceInputs["rules"] = state?.rules;
            resourceInputs["sourcePostureChecks"] = state?.sourcePostureChecks;
        } else {
            const args = argsOrState as PolicyArgs | undefined;
            resourceInputs["description"] = args?.description;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["name"] = args?.name;
            resourceInputs["rules"] = args?.rules;
            resourceInputs["sourcePostureChecks"] = args?.sourcePostureChecks;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Policy.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Policy resources.
 */
export interface PolicyState {
    /**
     * Policy Description
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Policy enabled
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Policy Name
     */
    name?: pulumi.Input<string | undefined>;
    rules?: pulumi.Input<pulumi.Input<inputs.PolicyRule>[] | undefined>;
    /**
     * Posture checks associated with policy
     */
    sourcePostureChecks?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

/**
 * The set of arguments for constructing a Policy resource.
 */
export interface PolicyArgs {
    /**
     * Policy Description
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Policy enabled
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Policy Name
     */
    name?: pulumi.Input<string | undefined>;
    rules?: pulumi.Input<pulumi.Input<inputs.PolicyRule>[] | undefined>;
    /**
     * Posture checks associated with policy
     */
    sourcePostureChecks?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}
