// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class PostureCheck extends pulumi.CustomResource {
    /**
     * Get an existing PostureCheck resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PostureCheckState, opts?: pulumi.CustomResourceOptions): PostureCheck {
        return new PostureCheck(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netbird:index/postureCheck:PostureCheck';

    /**
     * Returns true if the given object is an instance of PostureCheck.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PostureCheck {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PostureCheck.__pulumiType;
    }

    /**
     * PostureCheck description
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    declare public readonly geoLocationCheck: pulumi.Output<outputs.PostureCheckGeoLocationCheck | undefined>;
    /**
     * PostureCheck Name
     */
    declare public readonly name: pulumi.Output<string>;
    declare public readonly netbirdVersionCheck: pulumi.Output<outputs.PostureCheckNetbirdVersionCheck | undefined>;
    declare public readonly osVersionCheck: pulumi.Output<outputs.PostureCheckOsVersionCheck | undefined>;
    declare public readonly peerNetworkRangeCheck: pulumi.Output<outputs.PostureCheckPeerNetworkRangeCheck | undefined>;
    declare public readonly processChecks: pulumi.Output<outputs.PostureCheckProcessCheck[] | undefined>;

    /**
     * Create a PostureCheck resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PostureCheckArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PostureCheckArgs | PostureCheckState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PostureCheckState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["geoLocationCheck"] = state?.geoLocationCheck;
            resourceInputs["name"] = state?.name;
            resourceInputs["netbirdVersionCheck"] = state?.netbirdVersionCheck;
            resourceInputs["osVersionCheck"] = state?.osVersionCheck;
            resourceInputs["peerNetworkRangeCheck"] = state?.peerNetworkRangeCheck;
            resourceInputs["processChecks"] = state?.processChecks;
        } else {
            const args = argsOrState as PostureCheckArgs | undefined;
            resourceInputs["description"] = args?.description;
            resourceInputs["geoLocationCheck"] = args?.geoLocationCheck;
            resourceInputs["name"] = args?.name;
            resourceInputs["netbirdVersionCheck"] = args?.netbirdVersionCheck;
            resourceInputs["osVersionCheck"] = args?.osVersionCheck;
            resourceInputs["peerNetworkRangeCheck"] = args?.peerNetworkRangeCheck;
            resourceInputs["processChecks"] = args?.processChecks;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PostureCheck.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering PostureCheck resources.
 */
export interface PostureCheckState {
    /**
     * PostureCheck description
     */
    description?: pulumi.Input<string | undefined>;
    geoLocationCheck?: pulumi.Input<inputs.PostureCheckGeoLocationCheck | undefined>;
    /**
     * PostureCheck Name
     */
    name?: pulumi.Input<string | undefined>;
    netbirdVersionCheck?: pulumi.Input<inputs.PostureCheckNetbirdVersionCheck | undefined>;
    osVersionCheck?: pulumi.Input<inputs.PostureCheckOsVersionCheck | undefined>;
    peerNetworkRangeCheck?: pulumi.Input<inputs.PostureCheckPeerNetworkRangeCheck | undefined>;
    processChecks?: pulumi.Input<pulumi.Input<inputs.PostureCheckProcessCheck>[] | undefined>;
}

/**
 * The set of arguments for constructing a PostureCheck resource.
 */
export interface PostureCheckArgs {
    /**
     * PostureCheck description
     */
    description?: pulumi.Input<string | undefined>;
    geoLocationCheck?: pulumi.Input<inputs.PostureCheckGeoLocationCheck | undefined>;
    /**
     * PostureCheck Name
     */
    name?: pulumi.Input<string | undefined>;
    netbirdVersionCheck?: pulumi.Input<inputs.PostureCheckNetbirdVersionCheck | undefined>;
    osVersionCheck?: pulumi.Input<inputs.PostureCheckOsVersionCheck | undefined>;
    peerNetworkRangeCheck?: pulumi.Input<inputs.PostureCheckPeerNetworkRangeCheck | undefined>;
    processChecks?: pulumi.Input<pulumi.Input<inputs.PostureCheckProcessCheck>[] | undefined>;
}
