// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ReverseProxyDomain extends pulumi.CustomResource {
    /**
     * Get an existing ReverseProxyDomain resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ReverseProxyDomainState, opts?: pulumi.CustomResourceOptions): ReverseProxyDomain {
        return new ReverseProxyDomain(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netbird:index/reverseProxyDomain:ReverseProxyDomain';

    /**
     * Returns true if the given object is an instance of ReverseProxyDomain.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ReverseProxyDomain {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ReverseProxyDomain.__pulumiType;
    }

    /**
     * Domain name
     */
    declare public readonly domain: pulumi.Output<string>;
    /**
     * The proxy cluster this domain should be validated against
     */
    declare public readonly targetCluster: pulumi.Output<string>;
    /**
     * Type of reverse proxy domain (free, custom)
     */
    declare public /*out*/ readonly type: pulumi.Output<string>;
    /**
     * Whether the domain has been validated
     */
    declare public /*out*/ readonly validated: pulumi.Output<boolean>;

    /**
     * Create a ReverseProxyDomain resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ReverseProxyDomainArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ReverseProxyDomainArgs | ReverseProxyDomainState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ReverseProxyDomainState | undefined;
            resourceInputs["domain"] = state?.domain;
            resourceInputs["targetCluster"] = state?.targetCluster;
            resourceInputs["type"] = state?.type;
            resourceInputs["validated"] = state?.validated;
        } else {
            const args = argsOrState as ReverseProxyDomainArgs | undefined;
            if (args?.domain === undefined && !opts.urn) {
                throw new Error("Missing required property 'domain'");
            }
            if (args?.targetCluster === undefined && !opts.urn) {
                throw new Error("Missing required property 'targetCluster'");
            }
            resourceInputs["domain"] = args?.domain;
            resourceInputs["targetCluster"] = args?.targetCluster;
            resourceInputs["type"] = undefined /*out*/;
            resourceInputs["validated"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ReverseProxyDomain.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ReverseProxyDomain resources.
 */
export interface ReverseProxyDomainState {
    /**
     * Domain name
     */
    domain?: pulumi.Input<string | undefined>;
    /**
     * The proxy cluster this domain should be validated against
     */
    targetCluster?: pulumi.Input<string | undefined>;
    /**
     * Type of reverse proxy domain (free, custom)
     */
    type?: pulumi.Input<string | undefined>;
    /**
     * Whether the domain has been validated
     */
    validated?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a ReverseProxyDomain resource.
 */
export interface ReverseProxyDomainArgs {
    /**
     * Domain name
     */
    domain: pulumi.Input<string>;
    /**
     * The proxy cluster this domain should be validated against
     */
    targetCluster: pulumi.Input<string>;
}
