// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Scim extends pulumi.CustomResource {
    /**
     * Get an existing Scim resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ScimState, opts?: pulumi.CustomResourceOptions): Scim {
        return new Scim(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netbird:index/scim:Scim';

    /**
     * Returns true if the given object is an instance of Scim.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Scim {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Scim.__pulumiType;
    }

    /**
     * SCIM API token (only available in full after creation)
     */
    declare public /*out*/ readonly authToken: pulumi.Output<string>;
    /**
     * Indicates whether the integration is enabled
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * List of<span pulumi-lang-nodejs=" startWith " pulumi-lang-dotnet=" StartWith " pulumi-lang-go=" startWith " pulumi-lang-python=" start_with " pulumi-lang-yaml=" startWith " pulumi-lang-java=" startWith " pulumi-lang-hcl=" start_with "> startWith </span>string patterns for groups to sync
     */
    declare public readonly groupPrefixes: pulumi.Output<string[]>;
    /**
     * Timestamp of when the integration was last synced
     */
    declare public /*out*/ readonly lastSyncedAt: pulumi.Output<string>;
    /**
     * The connection prefix used for the SCIM provider.
     */
    declare public readonly prefix: pulumi.Output<string>;
    /**
     * Name of the SCIM identity provider
     */
    declare public readonly providerName: pulumi.Output<string>;
    /**
     * List of<span pulumi-lang-nodejs=" startWith " pulumi-lang-dotnet=" StartWith " pulumi-lang-go=" startWith " pulumi-lang-python=" start_with " pulumi-lang-yaml=" startWith " pulumi-lang-java=" startWith " pulumi-lang-hcl=" start_with "> startWith </span>string patterns for groups which users to sync
     */
    declare public readonly userGroupPrefixes: pulumi.Output<string[]>;

    /**
     * Create a Scim resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ScimArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ScimArgs | ScimState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ScimState | undefined;
            resourceInputs["authToken"] = state?.authToken;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["groupPrefixes"] = state?.groupPrefixes;
            resourceInputs["lastSyncedAt"] = state?.lastSyncedAt;
            resourceInputs["prefix"] = state?.prefix;
            resourceInputs["providerName"] = state?.providerName;
            resourceInputs["userGroupPrefixes"] = state?.userGroupPrefixes;
        } else {
            const args = argsOrState as ScimArgs | undefined;
            if (args?.providerName === undefined && !opts.urn) {
                throw new Error("Missing required property 'providerName'");
            }
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["groupPrefixes"] = args?.groupPrefixes;
            resourceInputs["prefix"] = args?.prefix;
            resourceInputs["providerName"] = args?.providerName;
            resourceInputs["userGroupPrefixes"] = args?.userGroupPrefixes;
            resourceInputs["authToken"] = undefined /*out*/;
            resourceInputs["lastSyncedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["authToken"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Scim.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Scim resources.
 */
export interface ScimState {
    /**
     * SCIM API token (only available in full after creation)
     */
    authToken?: pulumi.Input<string | undefined>;
    /**
     * Indicates whether the integration is enabled
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * List of<span pulumi-lang-nodejs=" startWith " pulumi-lang-dotnet=" StartWith " pulumi-lang-go=" startWith " pulumi-lang-python=" start_with " pulumi-lang-yaml=" startWith " pulumi-lang-java=" startWith " pulumi-lang-hcl=" start_with "> startWith </span>string patterns for groups to sync
     */
    groupPrefixes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Timestamp of when the integration was last synced
     */
    lastSyncedAt?: pulumi.Input<string | undefined>;
    /**
     * The connection prefix used for the SCIM provider.
     */
    prefix?: pulumi.Input<string | undefined>;
    /**
     * Name of the SCIM identity provider
     */
    providerName?: pulumi.Input<string | undefined>;
    /**
     * List of<span pulumi-lang-nodejs=" startWith " pulumi-lang-dotnet=" StartWith " pulumi-lang-go=" startWith " pulumi-lang-python=" start_with " pulumi-lang-yaml=" startWith " pulumi-lang-java=" startWith " pulumi-lang-hcl=" start_with "> startWith </span>string patterns for groups which users to sync
     */
    userGroupPrefixes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

/**
 * The set of arguments for constructing a Scim resource.
 */
export interface ScimArgs {
    /**
     * Indicates whether the integration is enabled
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * List of<span pulumi-lang-nodejs=" startWith " pulumi-lang-dotnet=" StartWith " pulumi-lang-go=" startWith " pulumi-lang-python=" start_with " pulumi-lang-yaml=" startWith " pulumi-lang-java=" startWith " pulumi-lang-hcl=" start_with "> startWith </span>string patterns for groups to sync
     */
    groupPrefixes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The connection prefix used for the SCIM provider.
     */
    prefix?: pulumi.Input<string | undefined>;
    /**
     * Name of the SCIM identity provider
     */
    providerName: pulumi.Input<string>;
    /**
     * List of<span pulumi-lang-nodejs=" startWith " pulumi-lang-dotnet=" StartWith " pulumi-lang-go=" startWith " pulumi-lang-python=" start_with " pulumi-lang-yaml=" startWith " pulumi-lang-java=" startWith " pulumi-lang-hcl=" start_with "> startWith </span>string patterns for groups which users to sync
     */
    userGroupPrefixes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}
