// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SetupKey extends pulumi.CustomResource {
    /**
     * Get an existing SetupKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SetupKeyState, opts?: pulumi.CustomResourceOptions): SetupKey {
        return new SetupKey(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netbird:index/setupKey:SetupKey';

    /**
     * Returns true if the given object is an instance of SetupKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SetupKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SetupKey.__pulumiType;
    }

    /**
     * Allow extra DNS labels to be added to the peer
     */
    declare public readonly allowExtraDnsLabels: pulumi.Output<boolean>;
    /**
     * List of groups to automatically assign to peers created through this setup key
     */
    declare public readonly autoGroups: pulumi.Output<string[]>;
    /**
     * Indicate that the peer will be ephemeral or not, ephemeral peers are deleted after 10 minutes of inactivity
     */
    declare public readonly ephemeral: pulumi.Output<boolean>;
    /**
     * SetupKey Expiration Date
     */
    declare public /*out*/ readonly expires: pulumi.Output<string>;
    /**
     * Expiry time in seconds (0 is unlimited). The API reports an absolute expiry date and no creation date, so this value cannot be read back and an imported key adopts whatever the configuration says.
     */
    declare public readonly expirySeconds: pulumi.Output<number>;
    /**
     * Plaintext setup key
     */
    declare public /*out*/ readonly key: pulumi.Output<string>;
    /**
     * Last usage time
     */
    declare public /*out*/ readonly lastUsed: pulumi.Output<string>;
    /**
     * SetupKey Name
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Set to true to revoke setup key
     */
    declare public readonly revoked: pulumi.Output<boolean>;
    /**
     * Setup key state (valid or expired)
     */
    declare public /*out*/ readonly state: pulumi.Output<string>;
    /**
     * Setup Key type (one-off or reusable)
     */
    declare public readonly type: pulumi.Output<string>;
    /**
     * Creation timestamp
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;
    /**
     * Maximum number of times SetupKey can be used (0 for unlimited). A one-off key is always limited to 1 by the server, so leave this unset for one-off keys.
     */
    declare public readonly usageLimit: pulumi.Output<number>;
    /**
     * Number of times Setup Key was used
     */
    declare public /*out*/ readonly usedTimes: pulumi.Output<number>;
    /**
     * True if setup key can be used to create more Peers
     */
    declare public /*out*/ readonly valid: pulumi.Output<boolean>;

    /**
     * Create a SetupKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: SetupKeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SetupKeyArgs | SetupKeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SetupKeyState | undefined;
            resourceInputs["allowExtraDnsLabels"] = state?.allowExtraDnsLabels;
            resourceInputs["autoGroups"] = state?.autoGroups;
            resourceInputs["ephemeral"] = state?.ephemeral;
            resourceInputs["expires"] = state?.expires;
            resourceInputs["expirySeconds"] = state?.expirySeconds;
            resourceInputs["key"] = state?.key;
            resourceInputs["lastUsed"] = state?.lastUsed;
            resourceInputs["name"] = state?.name;
            resourceInputs["revoked"] = state?.revoked;
            resourceInputs["state"] = state?.state;
            resourceInputs["type"] = state?.type;
            resourceInputs["updatedAt"] = state?.updatedAt;
            resourceInputs["usageLimit"] = state?.usageLimit;
            resourceInputs["usedTimes"] = state?.usedTimes;
            resourceInputs["valid"] = state?.valid;
        } else {
            const args = argsOrState as SetupKeyArgs | undefined;
            resourceInputs["allowExtraDnsLabels"] = args?.allowExtraDnsLabels;
            resourceInputs["autoGroups"] = args?.autoGroups;
            resourceInputs["ephemeral"] = args?.ephemeral;
            resourceInputs["expirySeconds"] = args?.expirySeconds;
            resourceInputs["name"] = args?.name;
            resourceInputs["revoked"] = args?.revoked;
            resourceInputs["type"] = args?.type;
            resourceInputs["usageLimit"] = args?.usageLimit;
            resourceInputs["expires"] = undefined /*out*/;
            resourceInputs["key"] = undefined /*out*/;
            resourceInputs["lastUsed"] = undefined /*out*/;
            resourceInputs["state"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
            resourceInputs["usedTimes"] = undefined /*out*/;
            resourceInputs["valid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["key"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(SetupKey.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SetupKey resources.
 */
export interface SetupKeyState {
    /**
     * Allow extra DNS labels to be added to the peer
     */
    allowExtraDnsLabels?: pulumi.Input<boolean | undefined>;
    /**
     * List of groups to automatically assign to peers created through this setup key
     */
    autoGroups?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Indicate that the peer will be ephemeral or not, ephemeral peers are deleted after 10 minutes of inactivity
     */
    ephemeral?: pulumi.Input<boolean | undefined>;
    /**
     * SetupKey Expiration Date
     */
    expires?: pulumi.Input<string | undefined>;
    /**
     * Expiry time in seconds (0 is unlimited). The API reports an absolute expiry date and no creation date, so this value cannot be read back and an imported key adopts whatever the configuration says.
     */
    expirySeconds?: pulumi.Input<number | undefined>;
    /**
     * Plaintext setup key
     */
    key?: pulumi.Input<string | undefined>;
    /**
     * Last usage time
     */
    lastUsed?: pulumi.Input<string | undefined>;
    /**
     * SetupKey Name
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Set to true to revoke setup key
     */
    revoked?: pulumi.Input<boolean | undefined>;
    /**
     * Setup key state (valid or expired)
     */
    state?: pulumi.Input<string | undefined>;
    /**
     * Setup Key type (one-off or reusable)
     */
    type?: pulumi.Input<string | undefined>;
    /**
     * Creation timestamp
     */
    updatedAt?: pulumi.Input<string | undefined>;
    /**
     * Maximum number of times SetupKey can be used (0 for unlimited). A one-off key is always limited to 1 by the server, so leave this unset for one-off keys.
     */
    usageLimit?: pulumi.Input<number | undefined>;
    /**
     * Number of times Setup Key was used
     */
    usedTimes?: pulumi.Input<number | undefined>;
    /**
     * True if setup key can be used to create more Peers
     */
    valid?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a SetupKey resource.
 */
export interface SetupKeyArgs {
    /**
     * Allow extra DNS labels to be added to the peer
     */
    allowExtraDnsLabels?: pulumi.Input<boolean | undefined>;
    /**
     * List of groups to automatically assign to peers created through this setup key
     */
    autoGroups?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Indicate that the peer will be ephemeral or not, ephemeral peers are deleted after 10 minutes of inactivity
     */
    ephemeral?: pulumi.Input<boolean | undefined>;
    /**
     * Expiry time in seconds (0 is unlimited). The API reports an absolute expiry date and no creation date, so this value cannot be read back and an imported key adopts whatever the configuration says.
     */
    expirySeconds?: pulumi.Input<number | undefined>;
    /**
     * SetupKey Name
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Set to true to revoke setup key
     */
    revoked?: pulumi.Input<boolean | undefined>;
    /**
     * Setup Key type (one-off or reusable)
     */
    type?: pulumi.Input<string | undefined>;
    /**
     * Maximum number of times SetupKey can be used (0 for unlimited). A one-off key is always limited to 1 by the server, so leave this unset for one-off keys.
     */
    usageLimit?: pulumi.Input<number | undefined>;
}
