// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Token extends pulumi.CustomResource {
    /**
     * Get an existing Token resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TokenState, opts?: pulumi.CustomResourceOptions): Token {
        return new Token(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netbird:index/token:Token';

    /**
     * Returns true if the given object is an instance of Token.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Token {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Token.__pulumiType;
    }

    /**
     * Creation timestamp
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Token Expiration Date
     */
    declare public /*out*/ readonly expirationDate: pulumi.Output<string>;
    declare public readonly expirationDays: pulumi.Output<number>;
    /**
     * Last usage time
     */
    declare public /*out*/ readonly lastUsed: pulumi.Output<string>;
    /**
     * Token Name
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Plaintext token
     */
    declare public /*out*/ readonly token: pulumi.Output<string>;
    /**
     * User ID
     */
    declare public readonly userId: pulumi.Output<string>;

    /**
     * Create a Token resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TokenArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TokenArgs | TokenState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TokenState | undefined;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["expirationDate"] = state?.expirationDate;
            resourceInputs["expirationDays"] = state?.expirationDays;
            resourceInputs["lastUsed"] = state?.lastUsed;
            resourceInputs["name"] = state?.name;
            resourceInputs["token"] = state?.token;
            resourceInputs["userId"] = state?.userId;
        } else {
            const args = argsOrState as TokenArgs | undefined;
            if (args?.expirationDays === undefined && !opts.urn) {
                throw new Error("Missing required property 'expirationDays'");
            }
            if (args?.userId === undefined && !opts.urn) {
                throw new Error("Missing required property 'userId'");
            }
            resourceInputs["expirationDays"] = args?.expirationDays;
            resourceInputs["name"] = args?.name;
            resourceInputs["userId"] = args?.userId;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["expirationDate"] = undefined /*out*/;
            resourceInputs["lastUsed"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Token.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Token resources.
 */
export interface TokenState {
    /**
     * Creation timestamp
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * Token Expiration Date
     */
    expirationDate?: pulumi.Input<string | undefined>;
    expirationDays?: pulumi.Input<number | undefined>;
    /**
     * Last usage time
     */
    lastUsed?: pulumi.Input<string | undefined>;
    /**
     * Token Name
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Plaintext token
     */
    token?: pulumi.Input<string | undefined>;
    /**
     * User ID
     */
    userId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Token resource.
 */
export interface TokenArgs {
    expirationDays: pulumi.Input<number>;
    /**
     * Token Name
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * User ID
     */
    userId: pulumi.Input<string>;
}
