// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class User extends pulumi.CustomResource {
    /**
     * Get an existing User resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: UserState, opts?: pulumi.CustomResourceOptions): User {
        return new User(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netbird:index/user:User';

    /**
     * Returns true if the given object is an instance of User.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is User {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === User.__pulumiType;
    }

    /**
     * Group IDs to auto-assign to peers registered by this user
     */
    declare public readonly autoGroups: pulumi.Output<string[]>;
    /**
     * User Email
     */
    declare public readonly email: pulumi.Output<string>;
    /**
     * If set to true then user is blocked and can't use the system
     */
    declare public readonly isBlocked: pulumi.Output<boolean>;
    /**
     * Set to true if the caller user is the same as the resource user
     */
    declare public /*out*/ readonly isCurrent: pulumi.Output<boolean>;
    /**
     * If set to true, creates a Service Account User
     */
    declare public readonly isServiceUser: pulumi.Output<boolean>;
    /**
     * User issue method
     */
    declare public /*out*/ readonly issued: pulumi.Output<string>;
    /**
     * User Last Login timedate
     */
    declare public /*out*/ readonly lastLogin: pulumi.Output<string>;
    /**
     * User Name
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * User's NetBird account role (owner|admin|user|billing_admin|auditor|network_admin).
     */
    declare public readonly role: pulumi.Output<string>;
    /**
     * User status (active, invited or blocked)
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;

    /**
     * Create a User resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: UserArgs | UserState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as UserState | undefined;
            resourceInputs["autoGroups"] = state?.autoGroups;
            resourceInputs["email"] = state?.email;
            resourceInputs["isBlocked"] = state?.isBlocked;
            resourceInputs["isCurrent"] = state?.isCurrent;
            resourceInputs["isServiceUser"] = state?.isServiceUser;
            resourceInputs["issued"] = state?.issued;
            resourceInputs["lastLogin"] = state?.lastLogin;
            resourceInputs["name"] = state?.name;
            resourceInputs["role"] = state?.role;
            resourceInputs["status"] = state?.status;
        } else {
            const args = argsOrState as UserArgs | undefined;
            if (args?.isServiceUser === undefined && !opts.urn) {
                throw new Error("Missing required property 'isServiceUser'");
            }
            resourceInputs["autoGroups"] = args?.autoGroups;
            resourceInputs["email"] = args?.email;
            resourceInputs["isBlocked"] = args?.isBlocked;
            resourceInputs["isServiceUser"] = args?.isServiceUser;
            resourceInputs["name"] = args?.name;
            resourceInputs["role"] = args?.role;
            resourceInputs["isCurrent"] = undefined /*out*/;
            resourceInputs["issued"] = undefined /*out*/;
            resourceInputs["lastLogin"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(User.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering User resources.
 */
export interface UserState {
    /**
     * Group IDs to auto-assign to peers registered by this user
     */
    autoGroups?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * User Email
     */
    email?: pulumi.Input<string | undefined>;
    /**
     * If set to true then user is blocked and can't use the system
     */
    isBlocked?: pulumi.Input<boolean | undefined>;
    /**
     * Set to true if the caller user is the same as the resource user
     */
    isCurrent?: pulumi.Input<boolean | undefined>;
    /**
     * If set to true, creates a Service Account User
     */
    isServiceUser?: pulumi.Input<boolean | undefined>;
    /**
     * User issue method
     */
    issued?: pulumi.Input<string | undefined>;
    /**
     * User Last Login timedate
     */
    lastLogin?: pulumi.Input<string | undefined>;
    /**
     * User Name
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * User's NetBird account role (owner|admin|user|billing_admin|auditor|network_admin).
     */
    role?: pulumi.Input<string | undefined>;
    /**
     * User status (active, invited or blocked)
     */
    status?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a User resource.
 */
export interface UserArgs {
    /**
     * Group IDs to auto-assign to peers registered by this user
     */
    autoGroups?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * User Email
     */
    email?: pulumi.Input<string | undefined>;
    /**
     * If set to true then user is blocked and can't use the system
     */
    isBlocked?: pulumi.Input<boolean | undefined>;
    /**
     * If set to true, creates a Service Account User
     */
    isServiceUser: pulumi.Input<boolean>;
    /**
     * User Name
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * User's NetBird account role (owner|admin|user|billing_admin|auditor|network_admin).
     */
    role?: pulumi.Input<string | undefined>;
}
