/**
 * The overlay's own account state — its settings, its groups, the keys devices
 * enrol with, the networks the routing peer carries and the DNS those peers use
 * — as resources of the NetBird provider, bridged from its Terraform one.
 *
 * **A bridged provider rather than a client written here.** Everything in this
 * file is state behind somebody else's API, and this repository already made
 * that call once: public DNS is `@pulumi/cloudflare`'s records rather than a
 * hand-written API client to keep abreast of. The same arithmetic holds here
 * and more sharply — the provider ships twenty-four resource types and
 * twenty-five data sources, each with a real `read` and a real `diff`, which is
 * what makes a group renamed in the
 * dashboard drift on a refresh and a retired route a deletion in the deploy
 * that retired it. The old repository's reconciler was five hundred lines of
 * GET-then-POST-then-PUT that only ever converged forward: it created what was
 * missing and corrected what had drifted, and could not delete, because a
 * list-and-compare has no way to tell a resource somebody else made from one it
 * made and has since stopped declaring. The SDK is generated by
 * `pulumi package add terraform-provider netbirdio/netbird` and committed under
 * `sdks/`, so a clone installs it and nothing is fetched at deploy time.
 *
 * **The token comes from the resource that minted it, not from the
 * environment.** `BootstrapAccount` claims the coordinator and returns the
 * access token as a secret output; that output configures the provider
 * constructed here. Nothing is exported to the process, nothing is read out of
 * a vault field, and there is no step where a person pastes a credential. It is
 * also what orders this whole file behind the account: a provider cannot be
 * configured before its token resolves, and the token does not resolve before
 * the coordinator has been claimed.
 *
 * **And unlike everything else here, the API half talks from the deploy
 * machine.**
 * Every device provider reaches the board over ssh, and the two bootstrap
 * resources deliberately run their calls *on* the board so the coordinator is
 * dialled on its own loopback. A bridged provider is a plugin process that runs
 * where Pulumi runs, and it takes one address — so it dials the coordinator's
 * public vhost. That is the cost of the trade: this stack now needs to reach
 * that name from wherever the deploy is run, which on the LAN is the resolver's
 * own record and off it is the public one. Nothing else in this repository has
 * that requirement.
 *
 * **The routing peer is the exception, and it is a device.** The routes below
 * name a peer, a peer is a machine that has enrolled, and the machine here is
 * this board — so `MeshAgent` reaches it over ssh the way every other device
 * resource does, with the setup key sealed for its age identity. It is built
 * before the peer is looked up and the lookup is ordered behind it, which is
 * what keeps a fresh installation to one `up`.
 *
 * **Making a person an admin is not here, and cannot be.** The provider's `user`
 * resource creates one, and creating a user is an invitation — a second, local
 * account beside the federated one somebody already signs in with, since the
 * broker mints a subject from the user's id and the connector's and a federated
 * subject can never equal a local one. Promoting the person who is already there
 * means adopting a user this deploy did not create, which needs the id up front
 * as an import, and the id is not knowable until they have signed in once. So
 * the role is granted in the dashboard, once, by the owner the deploy claimed.
 */

import * as netbird from "@pulumi/netbird";
import * as pulumi from "@pulumi/pulumi";

import { type MeshState } from "../config/spec";
import MeshAgent from "./meshAgent";

/**
 * The board the coordinator runs on, for the one part of this that is not an API
 * call: the routing peer is this machine's own agent, and it is enrolled over
 * ssh like every other thing on a device.
 */
export type MeshBoard = {
  /** ssh_config alias. */
  host: string;
  /** Public half of the age identity there, for the sealed setup key. */
  ageRecipient?: string;
  /** Extra ssh arguments — an alternate config file, a jump host, a port. */
  sshArgs?: readonly string[];
};

export type MeshArgs = {
  /** The entry that declared the state. Every resource here is named after it. */
  name: string;
  /**
   * Where the provider dials the coordinator: its public origin, not the
   * loopback the board's own configuration uses. The provider wants the origin
   * and appends the API path itself — its default is the hosted service's, and
   * a self-hosted coordinator is the vhost in front of it.
   */
  origin: string;
  /** The account's access token, from the resource that claimed the account. */
  token: pulumi.Output<string>;
  state: MeshState;
  /** Where the routing peer is, when the state says the deploy enrols one. */
  board: MeshBoard;
};

/**
 * Everything the dashboard would otherwise have somebody click, declared.
 *
 * The order below is the order the account is built in, and every edge in it is
 * a value rather than a `dependsOn`: a setup key names the groups it drops a
 * peer into, a route names the groups it is offered to and the peer that
 * carries it, and a nameserver group names that same peer's overlay address.
 */
export default function declareMesh({ name, origin, token, state, board }: MeshArgs): void {
  // No `dependsOn` anywhere in here, and none is passed in: the token is the
  // ordering. It is an output of the resource that claimed the account, that
  // resource is ordered behind the service's own unit, and a provider cannot be
  // configured before its inputs resolve — so everything below is already after
  // a coordinator that answers.
  const provider = new netbird.Provider(`${name}-api`, { managementUrl: origin, token });
  // Every resource below is this provider's. Nothing is left to the ambient one,
  // which would configure itself from `NB_PAT` in the environment — a variable
  // nothing here sets and nobody should have to.
  const on: pulumi.CustomResourceOptions = { provider };

  /**
   * A group this deploy owns, created and therefore removable; or one it does
   * not, looked up.
   *
   * The overlay ships an `All` that holds every peer and that nothing here
   * created, so a declaration referring to it has to resolve a name to an id
   * without claiming it — a resource for it would be one Pulumi believes it may
   * replace, and replacing the group every route is offered to is every peer
   * losing its routes. Lookups are memoised because a name referenced by three
   * declarations is one question, and each `getGroupOutput` is a round-trip.
   */
  const declared = new Map<string, pulumi.Output<string>>(
    state.groups.map((group) => [
      group,
      new netbird.Group(`${name}-group-${group}`, { name: group }, on).id,
    ]),
  );
  const looked = new Map<string, pulumi.Output<string>>();
  const groupId = (group: string): pulumi.Output<string> => {
    const own = declared.get(group);
    if (own !== undefined) return own;
    let found = looked.get(group);
    if (found === undefined) {
      found = netbird.getGroupOutput({ name: group }, { provider }).apply((answer) => answer.id);
      looked.set(group, found);
    }
    return found;
  };
  const groupIds = (groups: readonly string[]): pulumi.Output<string>[] => groups.map(groupId);

  // The ranges and the policies that apply to every peer. A singleton on the
  // account rather than a thing there can be several of, so it takes the account
  // itself as its id and its `delete` is a no-op — there is no state where the
  // account has no settings.
  new netbird.AccountSettings(
    `${name}-settings`,
    {
      networkRange: state.settings.networkRange,
      dnsDomain: state.settings.dnsDomain,
      peerLoginExpirationEnabled: state.settings.peerLoginExpirationEnabled,
      routingPeerDnsResolutionEnabled: state.settings.routingPeerDnsResolutionEnabled,
      jwtGroupsEnabled: state.settings.jwtGroupsEnabled,
      jwtAllowGroups: [...state.settings.jwtAllowGroups],
    },
    on,
  );

  const keys = new Map<string, pulumi.Output<string>>(
    state.setupKeys.map((key) => [
      key.name,
      // `key` on the resource is the plaintext, and the provider marks it a
      // secret output — so it is in state under the stack passphrase and in no
      // vault, in no clipboard and in nobody's terminal. That is what makes the
      // board's own enrolment need no copying: it is read straight from here.
      new netbird.SetupKey(
        `${name}-key-${key.name}`,
        {
          name: key.name,
          type: key.type,
          expirySeconds: key.expirySeconds,
          usageLimit: key.usageLimit,
          autoGroups: groupIds(key.autoGroups),
          ephemeral: key.ephemeral,
        },
        on,
      ).key,
    ]),
  );

  /**
   * The board's own membership of the overlay it coordinates, which is what the
   * routes below are carried by.
   *
   * Everything else in this file is an API call from the deploy machine; this is
   * the one thing that happens on the board, so it takes the ssh alias and the
   * age identity the device providers take. It is built before the peer lookup
   * and handed to it as an ordering edge — so the first `up` on a fresh
   * installation enrols the agent and *then* resolves the peer, in one run,
   * rather than failing at a name it was about to create.
   *
   * That it happens after the coordinator answers is the key, again: the key's
   * plaintext is an output of a resource of this provider, the provider is
   * configured with the account's token, and the account is claimed against a
   * unit that has started. No `dependsOn` says so and none has to.
   */
  const enrolled = ((): MeshAgent | undefined => {
    if (state.agent === undefined) return undefined;
    const setupKey = keys.get(state.agent.setupKey);
    if (setupKey === undefined) {
      throw new Error(
        `the mesh's routing peer enrols with a key called '${state.agent.setupKey}', and the ` +
          `keys declared are ${state.setupKeys.map((key) => `'${key.name}'`).join(", ") || "none"}`,
      );
    }
    if (board.ageRecipient === undefined) {
      throw new Error(
        `${board.host} enrols on the mesh but has no ageRecipient — the setup key reaches the ` +
          "board sealed, so generate an identity on the host and record its public half",
      );
    }
    return new MeshAgent({
      name,
      host: board.host,
      sshArgs: board.sshArgs,
      ageRecipient: board.ageRecipient,
      // The public vhost, which is what every other peer dials and what the
      // server's own `exposedAddress` already says. Loopback would work from
      // this board alone and would be a path nothing else in the mesh takes.
      managementUrl: origin,
      // The name the routes are resolved against, stated once — see `MeshState`.
      hostname: state.routingPeer,
      setupKey,
      wireguardPort: state.agent.wireguardPort,
    });
  })();

  // Nothing below names the routing peer, so nothing below asks the coordinator
  // for it: a declaration that carries no network and answers no query costs no
  // lookup and cannot fail on a board whose agent has not enrolled.
  if (state.routes.length === 0 && state.nameservers.length === 0) return;

  /**
   * The board as the coordinator sees it, which is a peer like any other and
   * not something this deploy creates: a peer exists once the agent on the
   * machine has enrolled with one of the keys above.
   *
   * **Declared rather than made conditional, and it fails the deploy by name
   * while the agent is not there yet.** The alternative — skip the routes until
   * the peer shows up, which is what the old repository's reconciler did — is
   * the failure this repository refuses everywhere else: a mesh with no route to
   * the LAN behind it looks exactly like a working mesh from the outside. A
   * phone connects, the dashboard is green, and every name in the house times
   * out, with nothing anywhere having said that the thing which carries them was
   * never created. A run that stops here says so in one sentence instead.
   *
   * `dependsOn` on a lookup rather than on a resource, which is the whole reason
   * a fresh installation is still one `up`: the engine holds the invoke until
   * the enrolment above has run, and answers it as *unknown* during a preview,
   * where that resource does not exist yet. So a preview of a board that has
   * never enrolled plans the routes instead of throwing, and the apply resolves
   * them against the peer the same run just created.
   */
  const peer = netbird
    .getPeerOutput(
      { name: state.routingPeer },
      { provider, dependsOn: enrolled === undefined ? [] : [enrolled.enrolment] },
    )
    .apply((found) => {
      if (found.id === "" || found.ip === "") {
        throw new Error(
          `no peer on the overlay is called '${state.routingPeer}': the routes and the DNS ` +
            "below are carried by a peer of that name, so either this board's own agent enrols " +
            "under it or the machine that does has to be on the overlay first",
        );
      }
      return found;
    });

  for (const route of state.routes) {
    new netbird.Route(
      `${name}-route-${route.networkId}`,
      {
        networkId: route.networkId,
        description: route.description,
        network: route.network,
        peer: peer.apply((found) => found.id),
        groups: groupIds(route.groups),
        metric: route.metric,
        masquerade: route.masquerade,
        enabled: route.enabled,
        skipAutoApply: route.skipAutoApply ?? false,
      },
      on,
    );
  }

  for (const nameservers of state.nameservers) {
    new netbird.NameserverGroup(
      `${name}-dns-${nameservers.name}`,
      {
        name: nameservers.name,
        description: nameservers.description,
        // The routing peer's overlay address, read off the peer rather than
        // pinned: the coordinator assigns it, and a peer deleted and re-enrolled
        // is assigned another. A literal here would keep resolving to a hole and
        // the deploy would go on reporting it correct.
        nameservers: [
          { ip: peer.apply((found) => found.ip), nsType: "udp", port: nameservers.port },
        ],
        groups: groupIds(nameservers.groups),
        domains: [...nameservers.domains],
        enabled: nameservers.enabled,
        primary: nameservers.primary,
        searchDomainsEnabled: nameservers.searchDomainsEnabled,
      },
      on,
    );
  }
}
